2024-01-20 05:35:05,328 [DEBUG] Using selector: EpollSelector
2024-01-20 05:35:05,330 [INFO] logging in using static token
2024-01-20 05:35:06,556 [INFO] Shard ID 0 has connected to Gateway (Session ID: 0c19adc45f0959e88b3b7d5d4fe76cdd).
2024-01-20 05:35:08,563 [INFO] -------------
2024-01-20 05:35:08,563 [INFO] |Fantasy Bot|
2024-01-20 05:35:08,564 [INFO] -------------
2024-01-20 05:35:17,083 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 88, in on_message
    with open(file_name, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'draft_order/.txt'
2024-01-20 05:35:24,501 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fbf00b4ee30>
2024-01-20 05:35:30,476 [DEBUG] Using selector: EpollSelector
2024-01-20 05:35:30,476 [INFO] logging in using static token
2024-01-20 05:35:31,568 [INFO] Shard ID 0 has connected to Gateway (Session ID: 1e9818400daec759e4a383040a7d1c3b).
2024-01-20 05:35:33,576 [INFO] -------------
2024-01-20 05:35:33,576 [INFO] |Fantasy Bot|
2024-01-20 05:35:33,576 [INFO] -------------
2024-01-20 05:35:59,448 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f45ac91ae90>
2024-01-20 05:36:02,368 [DEBUG] Using selector: EpollSelector
2024-01-20 05:36:02,369 [INFO] logging in using static token
2024-01-20 05:36:03,604 [INFO] Shard ID 0 has connected to Gateway (Session ID: bc55c457ae55a74dd38678d4cac8988e).
2024-01-20 05:36:05,611 [INFO] -------------
2024-01-20 05:36:05,612 [INFO] |Fantasy Bot|
2024-01-20 05:36:05,612 [INFO] -------------
2024-01-20 05:36:48,634 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f017ca1ee30>
2024-01-20 05:36:53,515 [DEBUG] Using selector: EpollSelector
2024-01-20 05:36:53,516 [INFO] logging in using static token
2024-01-20 05:36:54,768 [INFO] Shard ID 0 has connected to Gateway (Session ID: 2e118b4070d60826cdf18856f52e86d7).
2024-01-20 05:36:56,775 [INFO] -------------
2024-01-20 05:36:56,775 [INFO] |Fantasy Bot|
2024-01-20 05:36:56,775 [INFO] -------------
2024-01-20 05:37:35,386 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0925772e90>
2024-01-20 05:37:37,938 [DEBUG] Using selector: EpollSelector
2024-01-20 05:37:37,939 [INFO] logging in using static token
2024-01-20 05:37:39,046 [INFO] Shard ID 0 has connected to Gateway (Session ID: aa6bc4a17ebee6eeda7b9bf9e8b3fae7).
2024-01-20 05:37:41,055 [INFO] -------------
2024-01-20 05:37:41,055 [INFO] |Fantasy Bot|
2024-01-20 05:37:41,055 [INFO] -------------
2024-01-20 05:38:15,956 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f7e6c9abd30>
2024-01-20 05:38:19,306 [DEBUG] Using selector: EpollSelector
2024-01-20 05:38:19,308 [INFO] logging in using static token
2024-01-20 05:38:20,483 [INFO] Shard ID 0 has connected to Gateway (Session ID: a553f36bca2405d167d7daa37c7868b3).
2024-01-20 05:38:22,495 [INFO] -------------
2024-01-20 05:38:22,495 [INFO] |Fantasy Bot|
2024-01-20 05:38:22,496 [INFO] -------------
2024-01-20 05:38:47,979 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f653a60ee00>
2024-01-20 05:48:30,010 [DEBUG] Using selector: EpollSelector
2024-01-20 05:48:30,011 [INFO] logging in using static token
2024-01-20 05:48:31,100 [INFO] Shard ID 0 has connected to Gateway (Session ID: 42f7ae59aaf22ce1348c021afd4c5600).
2024-01-20 05:48:33,116 [INFO] -------------
2024-01-20 05:48:33,116 [INFO] |Fantasy Bot|
2024-01-20 05:48:33,117 [INFO] -------------
2024-01-20 05:49:59,335 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe62e0deef0>
2024-01-20 07:00:48,280 [DEBUG] Using selector: EpollSelector
2024-01-20 07:00:48,281 [INFO] logging in using static token
2024-01-20 07:00:50,720 [INFO] Shard ID 0 has connected to Gateway (Session ID: 742ec6546256225268078adb0f911ef2).
2024-01-20 07:00:52,734 [INFO] -------------
2024-01-20 07:00:52,735 [INFO] |Fantasy Bot|
2024-01-20 07:00:52,735 [INFO] -------------
2024-01-20 07:01:12,306 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 84, in on_message
    current_datetime = datetime.datetime.now().strftime("%Y%m%d%H%M")
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2024-01-20 07:01:26,072 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff679302dd0>
2024-01-20 07:01:29,022 [DEBUG] Using selector: EpollSelector
2024-01-20 07:01:29,023 [INFO] logging in using static token
2024-01-20 07:01:30,140 [INFO] Shard ID 0 has connected to Gateway (Session ID: f4a192e068ebdee6190eca6685793c9f).
2024-01-20 07:01:32,149 [INFO] -------------
2024-01-20 07:01:32,150 [INFO] |Fantasy Bot|
2024-01-20 07:01:32,150 [INFO] -------------
2024-01-21 06:22:02,628 [DEBUG] Using selector: EpollSelector
2024-01-21 06:22:02,630 [INFO] logging in using static token
2024-01-21 06:22:03,691 [INFO] Shard ID 0 has connected to Gateway (Session ID: b526e4fd456175bd13f2c395df03ddf5).
2024-01-21 06:22:05,698 [INFO] -------------
2024-01-21 06:22:05,698 [INFO] |Fantasy Bot|
2024-01-21 06:22:05,699 [INFO] -------------
2024-01-21 06:25:46,280 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2f7afceec0>
2024-01-21 07:30:57,771 [DEBUG] Using selector: EpollSelector
2024-01-21 07:30:57,774 [INFO] logging in using static token
2024-01-21 07:30:58,865 [INFO] Shard ID 0 has connected to Gateway (Session ID: 84f277576622d72e7b79c5b5720cf416).
2024-01-21 07:31:00,886 [INFO] -------------
2024-01-21 07:31:00,887 [INFO] |Fantasy Bot|
2024-01-21 07:31:00,887 [INFO] -------------
2024-01-21 07:31:36,673 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fdb646d2b60>
2024-01-21 07:32:12,116 [DEBUG] Using selector: EpollSelector
2024-01-21 07:32:12,118 [INFO] logging in using static token
2024-01-21 07:32:13,369 [INFO] Shard ID 0 has connected to Gateway (Session ID: 198b804f02964eb4d528593044eec108).
2024-01-21 07:32:15,374 [INFO] -------------
2024-01-21 07:32:15,375 [INFO] |Fantasy Bot|
2024-01-21 07:32:15,375 [INFO] -------------
2024-01-21 08:32:40,446 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9320332e00>
2024-01-21 21:20:13,408 [DEBUG] Using selector: EpollSelector
2024-01-21 21:20:13,409 [INFO] logging in using static token
2024-01-21 21:20:14,726 [INFO] Shard ID 0 has connected to Gateway (Session ID: 05971f498c17845c4b2dea579a2a844f).
2024-01-21 21:20:16,734 [INFO] -------------
2024-01-21 21:20:16,735 [INFO] |Fantasy Bot|
2024-01-21 21:20:16,735 [INFO] -------------
2024-01-21 21:20:28,645 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 72, in on_message
    query = cursor.execute("""
sqlite3.OperationalError: no such table: closed_game_teams
2024-01-21 21:20:51,837 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 72, in on_message
    query = cursor.execute("""
sqlite3.OperationalError: no such table: closed_game_teams
2024-01-21 21:21:21,370 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fada08af370>
2024-01-21 21:22:03,157 [DEBUG] Using selector: EpollSelector
2024-01-21 21:22:03,158 [INFO] logging in using static token
2024-01-21 21:22:04,223 [INFO] Shard ID 0 has connected to Gateway (Session ID: 42e13c448373619a0edf46a629a80205).
2024-01-21 21:22:06,230 [INFO] -------------
2024-01-21 21:22:06,231 [INFO] |Fantasy Bot|
2024-01-21 21:22:06,231 [INFO] -------------
2024-01-21 21:22:12,562 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 939, in _finalize_columns_and_data
    columns = _validate_or_indexify_columns(contents, columns)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 986, in _validate_or_indexify_columns
    raise AssertionError(
AssertionError: 1 columns passed, passed data had 2 columns

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 81, in on_message
    df = pd.DataFrame(data, columns=columns)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 809, in __init__
    arrays, columns, index = nested_data_to_arrays(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 520, in nested_data_to_arrays
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 845, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 942, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 1 columns passed, passed data had 2 columns
2024-01-21 21:22:28,123 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe44b8b7340>
2024-01-21 21:22:30,866 [DEBUG] Using selector: EpollSelector
2024-01-21 21:22:30,867 [INFO] logging in using static token
2024-01-21 21:22:32,058 [INFO] Shard ID 0 has connected to Gateway (Session ID: 42893efdc39a239fef3f94fe60cec484).
2024-01-21 21:22:43,512 [DEBUG] Using selector: EpollSelector
2024-01-21 21:22:43,512 [INFO] logging in using static token
2024-01-21 21:22:44,641 [INFO] Shard ID 0 has connected to Gateway (Session ID: 6b97e209dd7862c957243eed11b5dccb).
2024-01-21 21:22:46,658 [INFO] -------------
2024-01-21 21:22:46,658 [INFO] |Fantasy Bot|
2024-01-21 21:22:46,658 [INFO] -------------
2024-01-21 21:23:05,489 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 80, in on_message
    embed = discord.Embed(title=f"{message.author.name}'s team: ", color=self.generate_random_color())
AttributeError: 'fantasyBotBackend' object has no attribute 'generate_random_color'
2024-01-21 21:23:57,690 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f642c0ab310>
2024-01-21 21:24:00,977 [DEBUG] Using selector: EpollSelector
2024-01-21 21:24:00,978 [INFO] logging in using static token
2024-01-21 21:24:02,883 [INFO] Shard ID 0 has connected to Gateway (Session ID: ec31a02ff79bc2824d1736612c990ae6).
2024-01-21 21:24:04,889 [INFO] -------------
2024-01-21 21:24:04,890 [INFO] |Fantasy Bot|
2024-01-21 21:24:04,890 [INFO] -------------
2024-01-21 21:24:22,228 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff8830532e0>
2024-01-21 21:24:50,898 [DEBUG] Using selector: EpollSelector
2024-01-21 21:24:50,900 [INFO] logging in using static token
2024-01-21 21:24:52,108 [INFO] Shard ID 0 has connected to Gateway (Session ID: 687f76ca34c27177092acfc8d41ec229).
2024-01-21 21:24:54,116 [INFO] -------------
2024-01-21 21:24:54,116 [INFO] |Fantasy Bot|
2024-01-21 21:24:54,116 [INFO] -------------
2024-01-21 21:25:08,140 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3bf1363370>
2024-01-21 21:30:50,157 [DEBUG] Using selector: EpollSelector
2024-01-21 21:30:50,158 [INFO] logging in using static token
2024-01-21 21:30:51,253 [INFO] Shard ID 0 has connected to Gateway (Session ID: 8a4e14d532ae6154ee86d2fb78db9c53).
2024-01-21 21:30:53,278 [INFO] -------------
2024-01-21 21:30:53,278 [INFO] |Fantasy Bot|
2024-01-21 21:30:53,279 [INFO] -------------
2024-01-21 21:31:05,511 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 85, in on_message
    query = cursor.execute("""SELECT p.player_id, p.player_name, p.player_team, p.role, SUM(pdp.total_points) AS max_daily_score
sqlite3.OperationalError: no such column: p.player_team
2024-01-21 21:31:13,601 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb82c593310>
2024-01-21 21:31:56,866 [DEBUG] Using selector: EpollSelector
2024-01-21 21:31:56,866 [INFO] logging in using static token
2024-01-21 21:31:57,992 [INFO] Shard ID 0 has connected to Gateway (Session ID: f129eb837adf92e3f7cba00cdcaa1648).
2024-01-21 21:31:59,997 [INFO] -------------
2024-01-21 21:31:59,998 [INFO] |Fantasy Bot|
2024-01-21 21:31:59,998 [INFO] -------------
2024-01-21 21:32:20,573 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 85, in on_message
    query = cursor.execute("""SELECT p.player_id, p.player_name, p.team, p.role, SUM(pdp.total_points) AS max_daily_score
sqlite3.OperationalError: no such column: p.team
2024-01-21 21:32:38,197 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f89271273d0>
2024-01-21 21:32:40,818 [DEBUG] Using selector: EpollSelector
2024-01-21 21:32:40,819 [INFO] logging in using static token
2024-01-21 21:32:42,095 [INFO] Shard ID 0 has connected to Gateway (Session ID: 9daf20f7b4b2d0ffe955e51c731119dc).
2024-01-21 21:32:44,100 [INFO] -------------
2024-01-21 21:32:44,101 [INFO] |Fantasy Bot|
2024-01-21 21:32:44,101 [INFO] -------------
2024-01-21 21:32:46,993 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 85, in on_message
    query = cursor.execute("""SELECT p.player_id, p.player_name, p.team, p.role, SUM(pdp.total_points) AS max_daily_score
sqlite3.OperationalError: no such column: p.team
2024-01-21 21:32:53,848 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6ecf45b2b0>
2024-01-21 21:32:56,397 [DEBUG] Using selector: EpollSelector
2024-01-21 21:32:56,398 [INFO] logging in using static token
2024-01-21 21:32:57,627 [INFO] Shard ID 0 has connected to Gateway (Session ID: 685beb24decaa4fe51b8f7f7d0812fbc).
2024-01-21 21:32:59,635 [INFO] -------------
2024-01-21 21:32:59,635 [INFO] |Fantasy Bot|
2024-01-21 21:32:59,635 [INFO] -------------
2024-01-21 21:33:02,586 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 102, in on_message
    await message.channel.send(embed=embed)
  File "/usr/local/lib/python3.10/dist-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.10/dist-packages/discord/http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.value: Must be 1024 or fewer in length.
2024-01-21 21:33:09,396 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f8f2b9b72e0>
2024-01-21 21:33:11,972 [DEBUG] Using selector: EpollSelector
2024-01-21 21:33:11,973 [INFO] logging in using static token
2024-01-21 21:33:14,238 [INFO] Shard ID 0 has connected to Gateway (Session ID: ea15405bf08ad5770dd7300db8c60c2e).
2024-01-21 21:33:16,247 [INFO] -------------
2024-01-21 21:33:16,247 [INFO] |Fantasy Bot|
2024-01-21 21:33:16,247 [INFO] -------------
2024-01-21 21:34:25,334 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3261cff340>
2024-01-21 21:35:00,389 [DEBUG] Using selector: EpollSelector
2024-01-21 21:35:00,390 [INFO] logging in using static token
2024-01-21 21:35:11,349 [DEBUG] Using selector: EpollSelector
2024-01-21 21:35:11,349 [INFO] logging in using static token
2024-01-21 21:35:12,650 [INFO] Shard ID 0 has connected to Gateway (Session ID: 507c677c81b67e903242d27fa10ef7fd).
2024-01-21 21:35:14,657 [INFO] -------------
2024-01-21 21:35:14,658 [INFO] |Fantasy Bot|
2024-01-21 21:35:14,658 [INFO] -------------
2024-01-21 21:35:15,085 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f838efa7340>
2024-01-21 21:35:27,101 [DEBUG] Using selector: EpollSelector
2024-01-21 21:35:27,101 [INFO] logging in using static token
2024-01-21 21:35:28,159 [INFO] Shard ID 0 has connected to Gateway (Session ID: cb1c42ce5175e63acabfba2a3c63b364).
2024-01-21 21:35:30,167 [INFO] -------------
2024-01-21 21:35:30,168 [INFO] |Fantasy Bot|
2024-01-21 21:35:30,168 [INFO] -------------
2024-01-21 21:35:36,656 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 939, in _finalize_columns_and_data
    columns = _validate_or_indexify_columns(contents, columns)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 986, in _validate_or_indexify_columns
    raise AssertionError(
AssertionError: 4 columns passed, passed data had 5 columns

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 97, in on_message
    df = pd.DataFrame(data, columns=columns)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 809, in __init__
    arrays, columns, index = nested_data_to_arrays(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 520, in nested_data_to_arrays
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 845, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 942, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 4 columns passed, passed data had 5 columns
2024-01-21 21:36:25,270 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff13a0cb370>
2024-01-21 21:36:27,746 [DEBUG] Using selector: EpollSelector
2024-01-21 21:36:27,746 [INFO] logging in using static token
2024-01-21 21:36:28,845 [INFO] Shard ID 0 has connected to Gateway (Session ID: d81422e6f894e5353e872f7548db67ab).
2024-01-21 21:36:30,850 [INFO] -------------
2024-01-21 21:36:30,851 [INFO] |Fantasy Bot|
2024-01-21 21:36:30,851 [INFO] -------------
2024-01-21 21:36:31,466 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 98, in on_message
    support_df = df.filter('Role' == 'support').head(5)[['Player ID', 'Player Name', 'Team Name', 'Total Score']]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5704, in filter
    items = Index(items).intersection(labels)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 524, in __new__
    raise cls._raise_scalar_data_error(data)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5265, in _raise_scalar_data_error
    raise TypeError(
TypeError: Index(...) must be called with a collection of some kind, False was passed
2024-01-21 21:37:18,814 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f916b6ff250>
2024-01-21 21:37:21,625 [DEBUG] Using selector: EpollSelector
2024-01-21 21:37:21,625 [INFO] logging in using static token
2024-01-21 21:37:22,733 [INFO] Shard ID 0 has connected to Gateway (Session ID: 1f19ce67d2643719f5468947c5f13863).
2024-01-21 21:37:24,739 [INFO] -------------
2024-01-21 21:37:24,739 [INFO] |Fantasy Bot|
2024-01-21 21:37:24,739 [INFO] -------------
2024-01-21 21:37:32,567 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 98, in on_message
    support_df = df.filter('Role' == 'support').head(5)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5704, in filter
    items = Index(items).intersection(labels)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 524, in __new__
    raise cls._raise_scalar_data_error(data)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5265, in _raise_scalar_data_error
    raise TypeError(
TypeError: Index(...) must be called with a collection of some kind, False was passed
2024-01-21 21:38:33,277 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2f4d7bb3a0>
2024-01-21 21:38:35,727 [DEBUG] Using selector: EpollSelector
2024-01-21 21:38:35,727 [INFO] logging in using static token
2024-01-21 21:38:36,837 [INFO] Shard ID 0 has connected to Gateway (Session ID: ea1fc541952c4ed0b4b4d01797010957).
2024-01-21 21:38:38,845 [INFO] -------------
2024-01-21 21:38:38,845 [INFO] |Fantasy Bot|
2024-01-21 21:38:38,845 [INFO] -------------
2024-01-21 21:38:45,594 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 98, in on_message
    support_df = df.filter('Role' == 'support')
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5704, in filter
    items = Index(items).intersection(labels)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 524, in __new__
    raise cls._raise_scalar_data_error(data)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5265, in _raise_scalar_data_error
    raise TypeError(
TypeError: Index(...) must be called with a collection of some kind, False was passed
2024-01-21 21:39:18,509 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f7b50693340>
2024-01-21 21:39:20,948 [DEBUG] Using selector: EpollSelector
2024-01-21 21:39:20,949 [INFO] logging in using static token
2024-01-21 21:39:22,007 [INFO] Shard ID 0 has connected to Gateway (Session ID: 77968ca103a7e7e7422133edeb99af12).
2024-01-21 21:39:24,015 [INFO] -------------
2024-01-21 21:39:24,015 [INFO] |Fantasy Bot|
2024-01-21 21:39:24,015 [INFO] -------------
2024-01-21 21:40:00,124 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f679c4ff370>
2024-01-21 21:40:17,710 [DEBUG] Using selector: EpollSelector
2024-01-21 21:40:17,710 [INFO] logging in using static token
2024-01-21 21:40:18,887 [INFO] Shard ID 0 has connected to Gateway (Session ID: 2f766e55ec5d1dfb04ecec6d3d144ebb).
2024-01-21 21:40:20,894 [INFO] -------------
2024-01-21 21:40:20,894 [INFO] |Fantasy Bot|
2024-01-21 21:40:20,895 [INFO] -------------
2024-01-21 21:40:46,092 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f768dec3340>
2024-01-21 21:40:48,495 [DEBUG] Using selector: EpollSelector
2024-01-21 21:40:48,496 [INFO] logging in using static token
2024-01-21 21:40:49,896 [INFO] Shard ID 0 has connected to Gateway (Session ID: 6ae09e796f3110961e867269b4e31b19).
2024-01-21 21:40:51,906 [INFO] -------------
2024-01-21 21:40:51,907 [INFO] |Fantasy Bot|
2024-01-21 21:40:51,907 [INFO] -------------
2024-01-21 21:41:01,469 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7febc58eb220>
2024-01-21 21:41:04,539 [DEBUG] Using selector: EpollSelector
2024-01-21 21:41:04,539 [INFO] logging in using static token
2024-01-21 21:41:05,815 [INFO] Shard ID 0 has connected to Gateway (Session ID: 599743def7bc5385e8a0b0219af01fbf).
2024-01-21 21:41:07,822 [INFO] -------------
2024-01-21 21:41:07,823 [INFO] |Fantasy Bot|
2024-01-21 21:41:07,823 [INFO] -------------
2024-01-21 21:41:22,482 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f4b1ff773d0>
2024-01-21 21:43:45,982 [DEBUG] Using selector: EpollSelector
2024-01-21 21:43:45,983 [INFO] logging in using static token
2024-01-21 21:43:47,988 [INFO] Shard ID 0 has connected to Gateway (Session ID: e4133d28028f7345b22e42d9a0151964).
2024-01-21 21:43:49,995 [INFO] -------------
2024-01-21 21:43:49,995 [INFO] |Fantasy Bot|
2024-01-21 21:43:49,995 [INFO] -------------
2024-01-21 21:45:51,331 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f14b18e32e0>
2024-01-21 21:46:01,214 [DEBUG] Using selector: EpollSelector
2024-01-21 21:46:01,214 [INFO] logging in using static token
2024-01-21 21:46:02,417 [INFO] Shard ID 0 has connected to Gateway (Session ID: 2b4fbfd4713a764bc322f6be5fe61654).
2024-01-21 21:46:04,425 [INFO] -------------
2024-01-21 21:46:04,425 [INFO] |Fantasy Bot|
2024-01-21 21:46:04,426 [INFO] -------------
2024-01-21 21:46:37,996 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb94b0431c0>
2024-01-21 21:46:40,493 [DEBUG] Using selector: EpollSelector
2024-01-21 21:46:40,494 [INFO] logging in using static token
2024-01-21 21:46:41,569 [INFO] Shard ID 0 has connected to Gateway (Session ID: b020c3d52bbdb8c8e74e67e097abeb35).
2024-01-21 21:46:43,576 [INFO] -------------
2024-01-21 21:46:43,576 [INFO] |Fantasy Bot|
2024-01-21 21:46:43,577 [INFO] -------------
2024-01-21 21:50:42,713 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f55888c3370>
2024-01-21 23:54:53,236 [DEBUG] Using selector: EpollSelector
2024-01-21 23:54:53,238 [INFO] logging in using static token
2024-01-21 23:54:54,410 [INFO] Shard ID 0 has connected to Gateway (Session ID: 113ba2abb8b87e4b48347b658abc2ccd).
2024-01-21 23:54:56,419 [INFO] -------------
2024-01-21 23:54:56,420 [INFO] |Fantasy Bot|
2024-01-21 23:54:56,420 [INFO] -------------
2024-01-21 23:55:25,968 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5338ddb250>
2024-01-21 23:59:18,623 [DEBUG] Using selector: EpollSelector
2024-01-21 23:59:18,624 [INFO] logging in using static token
2024-01-21 23:59:19,719 [INFO] Shard ID 0 has connected to Gateway (Session ID: a62cd7f2f4ff74185e7c3f190a6ffb13).
2024-01-21 23:59:21,726 [INFO] -------------
2024-01-21 23:59:21,726 [INFO] |Fantasy Bot|
2024-01-21 23:59:21,726 [INFO] -------------
2024-01-21 23:59:38,024 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fdc9a63b3a0>
2024-01-22 01:07:44,455 [DEBUG] Using selector: EpollSelector
2024-01-22 01:07:44,457 [INFO] logging in using static token
2024-01-22 01:07:45,632 [INFO] Shard ID 0 has connected to Gateway (Session ID: c006b2708765f08ea51ad14c243288b6).
2024-01-22 01:07:47,657 [INFO] -------------
2024-01-22 01:07:47,658 [INFO] |Fantasy Bot|
2024-01-22 01:07:47,658 [INFO] -------------
2024-01-22 01:07:57,453 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 187, in on_message
    df = pd.DataFrame(data, columns=columns)
UnboundLocalError: local variable 'data' referenced before assignment
2024-01-22 01:08:27,538 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff286947400>
2024-01-22 01:08:32,137 [DEBUG] Using selector: EpollSelector
2024-01-22 01:08:32,138 [INFO] logging in using static token
2024-01-22 01:08:33,393 [INFO] Shard ID 0 has connected to Gateway (Session ID: 5d670621a68a2d2a0cdb4e793195f6db).
2024-01-22 01:08:35,401 [INFO] -------------
2024-01-22 01:08:35,402 [INFO] |Fantasy Bot|
2024-01-22 01:08:35,402 [INFO] -------------
2024-01-22 01:08:40,033 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 194, in on_message
    query = cursor.execute(f"""SELECT
sqlite3.OperationalError: incomplete input
2024-01-22 01:09:03,139 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f4b63ef3370>
2024-01-22 01:09:06,740 [DEBUG] Using selector: EpollSelector
2024-01-22 01:09:06,741 [INFO] logging in using static token
2024-01-22 01:09:07,892 [INFO] Shard ID 0 has connected to Gateway (Session ID: 76b8dc48cb649ab1d7822d0d80c0fcc8).
2024-01-22 01:09:09,925 [INFO] -------------
2024-01-22 01:09:09,925 [INFO] |Fantasy Bot|
2024-01-22 01:09:09,925 [INFO] -------------
2024-01-22 01:10:38,990 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3ce8bff370>
2024-01-22 01:12:04,429 [DEBUG] Using selector: EpollSelector
2024-01-22 01:12:04,429 [INFO] logging in using static token
2024-01-22 01:12:05,465 [INFO] Shard ID 0 has connected to Gateway (Session ID: 7c0ed2545674a78096f9705d9067ac7c).
2024-01-22 01:12:07,473 [INFO] -------------
2024-01-22 01:12:07,473 [INFO] |Fantasy Bot|
2024-01-22 01:12:07,474 [INFO] -------------
2024-01-22 01:13:14,691 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5f4305f3d0>
2024-01-22 01:13:25,513 [DEBUG] Using selector: EpollSelector
2024-01-22 01:13:25,515 [INFO] logging in using static token
2024-01-22 01:13:26,511 [INFO] Shard ID 0 has connected to Gateway (Session ID: 3d7e69e01b5464b2f7fec26229235992).
2024-01-22 01:13:28,520 [INFO] -------------
2024-01-22 01:13:28,520 [INFO] |Fantasy Bot|
2024-01-22 01:13:28,520 [INFO] -------------
2024-01-22 01:14:32,145 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f847ae43370>
2024-01-22 01:14:35,974 [DEBUG] Using selector: EpollSelector
2024-01-22 01:14:35,975 [INFO] logging in using static token
2024-01-22 01:14:37,303 [INFO] Shard ID 0 has connected to Gateway (Session ID: 464875dda79728ec8fe73acf93c44409).
2024-01-22 01:14:39,310 [INFO] -------------
2024-01-22 01:14:39,310 [INFO] |Fantasy Bot|
2024-01-22 01:14:39,311 [INFO] -------------
2024-01-22 01:14:42,794 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 208, in on_message
    embed = discord.Embed(title=f"Incoming trade requests: ", color=self.generate_random_color(), text="To accept trade, use +trade accept <trade_id>")
TypeError: Embed.__init__() got an unexpected keyword argument 'text'
2024-01-22 01:15:24,859 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f73345d33a0>
2024-01-22 01:15:33,833 [DEBUG] Using selector: EpollSelector
2024-01-22 01:15:33,834 [INFO] logging in using static token
2024-01-22 01:15:34,978 [INFO] Shard ID 0 has connected to Gateway (Session ID: 224afc1ebf0e2db6333d9138aa38f317).
2024-01-22 01:15:36,986 [INFO] -------------
2024-01-22 01:15:36,986 [INFO] |Fantasy Bot|
2024-01-22 01:15:36,986 [INFO] -------------
2024-01-22 01:15:41,521 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 208, in on_message
    embed = discord.Embed(title=f"Incoming trade requests: ", color=self.generate_random_color(), value="To accept trade, use +trade accept <trade_id>")
TypeError: Embed.__init__() got an unexpected keyword argument 'value'
2024-01-22 01:16:06,745 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd278c47400>
2024-01-22 01:16:09,178 [DEBUG] Using selector: EpollSelector
2024-01-22 01:16:09,179 [INFO] logging in using static token
2024-01-22 01:16:10,250 [INFO] Shard ID 0 has connected to Gateway (Session ID: e8a43ee9b67882f785f9c8c29a069203).
2024-01-22 01:16:12,264 [INFO] -------------
2024-01-22 01:16:12,264 [INFO] |Fantasy Bot|
2024-01-22 01:16:12,264 [INFO] -------------
2024-01-22 01:17:11,686 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f13de0c7280>
2024-01-22 01:17:33,402 [DEBUG] Using selector: EpollSelector
2024-01-22 01:17:33,403 [INFO] logging in using static token
2024-01-22 01:17:34,450 [INFO] Shard ID 0 has connected to Gateway (Session ID: c2298c0819df636d59e6446a998c34c4).
2024-01-22 01:17:36,466 [INFO] -------------
2024-01-22 01:17:36,466 [INFO] |Fantasy Bot|
2024-01-22 01:17:36,466 [INFO] -------------
2024-01-22 01:19:54,477 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f249066f3a0>
2024-01-21 19:04:56,325 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:04:56,327 [INFO] logging in using static token
2024-01-21 19:04:57,429 [INFO] Shard ID 0 has connected to Gateway (Session ID: 337def8b7c5acb99cf5c046a798f74ad).
2024-01-21 19:04:59,441 [INFO] -------------
2024-01-21 19:04:59,441 [INFO] |Fantasy Bot|
2024-01-21 19:04:59,441 [INFO] -------------
2024-01-21 19:05:26,471 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 221, in on_message
    query = cursor.execute(f"""SELECT
            ^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: p.is_active
2024-01-21 19:05:31,204 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001C045E56030>
2024-01-21 19:06:20,341 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:06:20,342 [INFO] logging in using static token
2024-01-21 19:06:21,486 [INFO] Shard ID 0 has connected to Gateway (Session ID: 8618fa2799d72a385d5b7505bff8b175).
2024-01-21 19:06:23,496 [INFO] -------------
2024-01-21 19:06:23,496 [INFO] |Fantasy Bot|
2024-01-21 19:06:23,496 [INFO] -------------
2024-01-21 19:06:41,853 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 222, in on_message
    query = cursor.execute(f"""SELECT
            ^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near ".": syntax error
2024-01-21 19:06:46,226 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022F80420620>
2024-01-21 19:07:09,790 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:07:09,791 [INFO] logging in using static token
2024-01-21 19:07:11,035 [INFO] Shard ID 0 has connected to Gateway (Session ID: e6f43ec070e115bc5ef567511e2127c6).
2024-01-21 19:07:13,038 [INFO] -------------
2024-01-21 19:07:13,038 [INFO] |Fantasy Bot|
2024-01-21 19:07:13,038 [INFO] -------------
2024-01-21 19:07:15,294 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001BEEBAD5CD0>
2024-01-21 19:07:36,821 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:07:36,822 [INFO] logging in using static token
2024-01-21 19:07:38,014 [INFO] Shard ID 0 has connected to Gateway (Session ID: 360a25e0ebe10223b8dba1f0d23490a6).
2024-01-21 19:07:40,036 [INFO] -------------
2024-01-21 19:07:40,036 [INFO] |Fantasy Bot|
2024-01-21 19:07:40,036 [INFO] -------------
2024-01-21 19:08:41,526 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000169A5AE01A0>
2024-01-21 19:09:01,641 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:09:01,642 [INFO] logging in using static token
2024-01-21 19:09:02,684 [INFO] Shard ID 0 has connected to Gateway (Session ID: 33eb9ec1cc74e1110a1f3ab7ff4b491c).
2024-01-21 19:09:04,688 [INFO] -------------
2024-01-21 19:09:04,689 [INFO] |Fantasy Bot|
2024-01-21 19:09:04,689 [INFO] -------------
2024-01-21 19:09:20,572 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 939, in _finalize_columns_and_data
    columns = _validate_or_indexify_columns(contents, columns)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 986, in _validate_or_indexify_columns
    raise AssertionError(
AssertionError: 5 columns passed, passed data had 6 columns

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 234, in on_message
    df = pd.DataFrame(data, columns=columns)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\frame.py", line 840, in __init__
    arrays, columns, index = nested_data_to_arrays(
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 520, in nested_data_to_arrays
    arrays, columns = to_arrays(data, columns, dtype=dtype)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 845, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 942, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 5 columns passed, passed data had 6 columns
2024-01-21 19:09:36,761 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022C01FADC10>
2024-01-21 19:09:39,867 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:09:39,869 [INFO] logging in using static token
2024-01-21 19:09:41,082 [INFO] Shard ID 0 has connected to Gateway (Session ID: aac96e655e65af3c1ae9d64d00c02402).
2024-01-21 19:09:43,083 [INFO] -------------
2024-01-21 19:09:43,083 [INFO] |Fantasy Bot|
2024-01-21 19:09:43,083 [INFO] -------------
2024-01-21 19:09:50,200 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 153, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 182, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'eliminated'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 234, in on_message
    df['eliminated'] = df['eliminated'].map({1: True, 0: False})
                       ~~^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\indexes\base.py", line 3809, in get_loc
    raise KeyError(key) from err
KeyError: 'eliminated'
2024-01-21 19:09:54,225 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001923DADAAE0>
2024-01-21 19:10:11,583 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:10:11,585 [INFO] logging in using static token
2024-01-21 19:10:12,587 [INFO] Shard ID 0 has connected to Gateway (Session ID: 3968c0443359c7606835a654dbbb56e0).
2024-01-21 19:10:14,600 [INFO] -------------
2024-01-21 19:10:14,600 [INFO] |Fantasy Bot|
2024-01-21 19:10:14,600 [INFO] -------------
2024-01-21 19:18:41,918 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001EA9F058260>
2024-01-21 19:24:42,702 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:24:42,703 [INFO] logging in using static token
2024-01-21 19:24:43,822 [INFO] Shard ID 0 has connected to Gateway (Session ID: d434e2a0002629fc7b26c09bbe329dda).
2024-01-21 19:24:45,826 [INFO] -------------
2024-01-21 19:24:45,826 [INFO] |Fantasy Bot|
2024-01-21 19:24:45,826 [INFO] -------------
2024-01-21 19:25:41,243 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000199628D4260>
2024-01-21 19:25:44,215 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:25:44,216 [INFO] logging in using static token
2024-01-21 19:25:45,283 [INFO] Shard ID 0 has connected to Gateway (Session ID: 05f61f88de66ed510ae23f5a5ae4720f).
2024-01-21 19:25:47,292 [INFO] -------------
2024-01-21 19:25:47,292 [INFO] |Fantasy Bot|
2024-01-21 19:25:47,292 [INFO] -------------
2024-01-21 19:25:58,161 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002593C206BD0>
2024-01-21 19:26:00,931 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:26:00,932 [INFO] logging in using static token
2024-01-21 19:26:02,095 [INFO] Shard ID 0 has connected to Gateway (Session ID: c001b107811303e178569991303a8840).
2024-01-21 19:26:04,106 [INFO] -------------
2024-01-21 19:26:04,106 [INFO] |Fantasy Bot|
2024-01-21 19:26:04,106 [INFO] -------------
2024-01-21 19:27:36,745 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002327FB44C20>
2024-01-21 19:28:24,018 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:28:24,019 [INFO] logging in using static token
2024-01-21 19:28:25,100 [INFO] Shard ID 0 has connected to Gateway (Session ID: 3b7b186093bb759026308d7001b3028a).
2024-01-21 19:28:27,120 [INFO] -------------
2024-01-21 19:28:27,121 [INFO] |Fantasy Bot|
2024-01-21 19:28:27,121 [INFO] -------------
2024-01-21 19:30:29,361 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000283DCC714C0>
2024-01-21 19:31:03,969 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:31:03,970 [INFO] logging in using static token
2024-01-21 19:31:05,076 [INFO] Shard ID 0 has connected to Gateway (Session ID: 8d47e6ba04e3f4747efd19c8dbe1ea6b).
2024-01-21 19:31:07,098 [INFO] -------------
2024-01-21 19:31:07,098 [INFO] |Fantasy Bot|
2024-01-21 19:31:07,098 [INFO] -------------
2024-01-21 19:31:07,339 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 262, in on_message
    query = cursor.execute(f"""SELECT player_id FROM players WHERE requestedplayerid = '{requestedplayerid}'""")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: requestedplayerid
2024-01-21 19:31:18,387 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000286E41FBA10>
2024-01-21 19:31:21,645 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:31:21,646 [INFO] logging in using static token
2024-01-21 19:31:22,740 [INFO] Shard ID 0 has connected to Gateway (Session ID: bf2218ab49c431f8c8621641e79fed9f).
2024-01-21 19:31:24,757 [INFO] -------------
2024-01-21 19:31:24,757 [INFO] |Fantasy Bot|
2024-01-21 19:31:24,757 [INFO] -------------
2024-01-21 19:34:11,642 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022F3D4C8500>
2024-01-21 19:34:35,067 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:34:35,068 [INFO] logging in using static token
2024-01-21 19:34:36,182 [INFO] Shard ID 0 has connected to Gateway (Session ID: 67fd72b2882acd10b10a1e134d899bd6).
2024-01-21 19:34:38,212 [INFO] -------------
2024-01-21 19:34:38,212 [INFO] |Fantasy Bot|
2024-01-21 19:34:38,212 [INFO] -------------
2024-01-21 19:35:01,544 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D7E98740B0>
2024-01-21 19:35:48,327 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:35:48,328 [INFO] logging in using static token
2024-01-21 19:35:49,334 [INFO] Shard ID 0 has connected to Gateway (Session ID: 92d1a4885777e9fef860844c0d533080).
2024-01-21 19:35:51,351 [INFO] -------------
2024-01-21 19:35:51,351 [INFO] |Fantasy Bot|
2024-01-21 19:35:51,351 [INFO] -------------
2024-01-21 19:35:53,999 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 271, in on_message
    requestee_name = data[1]
                     ~~~~^^^
IndexError: tuple index out of range
2024-01-21 19:36:04,853 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002C36D6D4170>
2024-01-21 19:36:07,920 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:36:07,922 [INFO] logging in using static token
2024-01-21 19:36:09,056 [INFO] Shard ID 0 has connected to Gateway (Session ID: 6b84981f689e2bf06c895e0edf099ac5).
2024-01-21 19:36:11,066 [INFO] -------------
2024-01-21 19:36:11,067 [INFO] |Fantasy Bot|
2024-01-21 19:36:11,067 [INFO] -------------
2024-01-21 19:36:12,392 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 273, in on_message
    requestee_name = data[1]
                     ~~~~^^^
IndexError: tuple index out of range
2024-01-21 19:37:16,246 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000014458358230>
2024-01-21 19:37:23,012 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:37:23,013 [INFO] logging in using static token
2024-01-21 19:37:24,082 [INFO] Shard ID 0 has connected to Gateway (Session ID: 7052bd06b36fcae41afeee6f36282923).
2024-01-21 19:37:26,088 [INFO] -------------
2024-01-21 19:37:26,088 [INFO] |Fantasy Bot|
2024-01-21 19:37:26,088 [INFO] -------------
2024-01-21 19:39:52,992 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000023657576630>
2024-01-21 19:41:44,081 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:41:44,081 [INFO] logging in using static token
2024-01-21 19:41:45,288 [INFO] Shard ID 0 has connected to Gateway (Session ID: 43b9b930680ee5c87c6e5d2f59339b80).
2024-01-21 19:41:47,301 [INFO] -------------
2024-01-21 19:41:47,301 [INFO] |Fantasy Bot|
2024-01-21 19:41:47,301 [INFO] -------------
2024-01-21 19:41:58,443 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 246, in on_message
    myplayerid, requestedplayerid = parse_trade_request(message.content)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
2024-01-21 19:42:59,876 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022E9A2D24B0>
2024-01-21 19:50:23,994 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:50:23,995 [INFO] logging in using static token
2024-01-21 19:50:25,291 [INFO] Shard ID 0 has connected to Gateway (Session ID: 6e817e8ea246dffe1702dfe08c361b0e).
2024-01-21 19:50:27,332 [INFO] -------------
2024-01-21 19:50:27,332 [INFO] |Fantasy Bot|
2024-01-21 19:50:27,332 [INFO] -------------
2024-01-21 19:52:00,384 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024E351AEED0>
2024-01-21 22:37:56,178 [DEBUG] Using proactor: IocpProactor
2024-01-21 22:37:56,182 [INFO] logging in using static token
2024-01-21 22:37:57,376 [INFO] Shard ID 0 has connected to Gateway (Session ID: 5cab026bad2b009f667b4b3b43b5eac3).
2024-01-21 22:37:59,387 [INFO] -------------
2024-01-21 22:37:59,387 [INFO] |Fantasy Bot|
2024-01-21 22:37:59,387 [INFO] -------------
2024-01-21 22:38:24,402 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 304, in on_message
    cursor.execute(f"""UPDATE closed_game_teams SET is_action = False
sqlite3.OperationalError: no such column: is_action
2024-01-21 22:38:59,543 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DAA0B13320>
2024-01-21 22:39:24,658 [DEBUG] Using proactor: IocpProactor
2024-01-21 22:39:24,660 [INFO] logging in using static token
2024-01-21 22:39:25,686 [INFO] Shard ID 0 has connected to Gateway (Session ID: 7b4a546516d3d6ab6eb03788f5acd115).
2024-01-21 22:39:27,690 [INFO] -------------
2024-01-21 22:39:27,690 [INFO] |Fantasy Bot|
2024-01-21 22:39:27,690 [INFO] -------------
2024-01-21 22:39:58,874 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000175D3CAE030>
2024-01-21 22:41:53,032 [DEBUG] Using proactor: IocpProactor
2024-01-21 22:41:53,033 [INFO] logging in using static token
2024-01-21 22:41:54,177 [INFO] Shard ID 0 has connected to Gateway (Session ID: 57562ea3786f7da25e581df21451925a).
2024-01-21 22:41:56,181 [INFO] -------------
2024-01-21 22:41:56,181 [INFO] |Fantasy Bot|
2024-01-21 22:41:56,181 [INFO] -------------
2024-01-21 22:43:24,046 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 292, in on_message
    cursor.execute(f"""UPDATE closed_game_teams SET is_action = False WHERE player_id = {requester_player_id} and manager_id = {manager_id}""")
sqlite3.OperationalError: no such column: is_action
2024-01-21 22:44:47,238 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020846532BA0>
2024-01-21 22:44:59,922 [DEBUG] Using proactor: IocpProactor
2024-01-21 22:44:59,923 [INFO] logging in using static token
2024-01-21 22:45:01,021 [INFO] Shard ID 0 has connected to Gateway (Session ID: b52acb75c12768b6e7494002c616b083).
2024-01-21 22:45:03,041 [INFO] -------------
2024-01-21 22:45:03,041 [INFO] |Fantasy Bot|
2024-01-21 22:45:03,041 [INFO] -------------
2024-01-21 22:48:27,868 [INFO] Shard ID 0 has successfully RESUMED session b52acb75c12768b6e7494002c616b083.
2024-01-21 22:48:31,901 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002573837DBB0>
2024-01-21 22:53:29,802 [DEBUG] Using proactor: IocpProactor
2024-01-21 22:53:29,802 [INFO] logging in using static token
2024-01-21 22:53:30,834 [INFO] Shard ID 0 has connected to Gateway (Session ID: bf42365d1ab9bf7fee63fdc91dcf5aa2).
2024-01-21 22:53:32,849 [INFO] -------------
2024-01-21 22:53:32,849 [INFO] |Fantasy Bot|
2024-01-21 22:53:32,849 [INFO] -------------
2024-01-21 22:56:36,447 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 87, in on_message
    await message.channel.send(embed=embed)
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.value: Must be 1024 or fewer in length.
2024-01-21 22:56:58,930 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 87, in on_message
    await message.channel.send(embed=embed)
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.value: Must be 1024 or fewer in length.
2024-01-21 22:58:14,237 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022E1217CB60>
2024-01-21 22:58:22,265 [DEBUG] Using proactor: IocpProactor
2024-01-21 22:58:22,267 [INFO] logging in using static token
2024-01-21 22:58:23,239 [INFO] Shard ID 0 has connected to Gateway (Session ID: e7f4b933ed293a101459d01d7896e88a).
2024-01-21 22:58:25,251 [INFO] -------------
2024-01-21 22:58:25,251 [INFO] |Fantasy Bot|
2024-01-21 22:58:25,251 [INFO] -------------
2024-01-21 22:59:19,897 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020B28946300>
