2024-01-20 05:35:05,328 [DEBUG] Using selector: EpollSelector
2024-01-20 05:35:05,330 [INFO] logging in using static token
2024-01-20 05:35:06,556 [INFO] Shard ID 0 has connected to Gateway (Session ID: 0c19adc45f0959e88b3b7d5d4fe76cdd).
2024-01-20 05:35:08,563 [INFO] -------------
2024-01-20 05:35:08,563 [INFO] |Fantasy Bot|
2024-01-20 05:35:08,564 [INFO] -------------
2024-01-20 05:35:17,083 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 88, in on_message
    with open(file_name, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'draft_order/.txt'
2024-01-20 05:35:24,501 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fbf00b4ee30>
2024-01-20 05:35:30,476 [DEBUG] Using selector: EpollSelector
2024-01-20 05:35:30,476 [INFO] logging in using static token
2024-01-20 05:35:31,568 [INFO] Shard ID 0 has connected to Gateway (Session ID: 1e9818400daec759e4a383040a7d1c3b).
2024-01-20 05:35:33,576 [INFO] -------------
2024-01-20 05:35:33,576 [INFO] |Fantasy Bot|
2024-01-20 05:35:33,576 [INFO] -------------
2024-01-20 05:35:59,448 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f45ac91ae90>
2024-01-20 05:36:02,368 [DEBUG] Using selector: EpollSelector
2024-01-20 05:36:02,369 [INFO] logging in using static token
2024-01-20 05:36:03,604 [INFO] Shard ID 0 has connected to Gateway (Session ID: bc55c457ae55a74dd38678d4cac8988e).
2024-01-20 05:36:05,611 [INFO] -------------
2024-01-20 05:36:05,612 [INFO] |Fantasy Bot|
2024-01-20 05:36:05,612 [INFO] -------------
2024-01-20 05:36:48,634 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f017ca1ee30>
2024-01-20 05:36:53,515 [DEBUG] Using selector: EpollSelector
2024-01-20 05:36:53,516 [INFO] logging in using static token
2024-01-20 05:36:54,768 [INFO] Shard ID 0 has connected to Gateway (Session ID: 2e118b4070d60826cdf18856f52e86d7).
2024-01-20 05:36:56,775 [INFO] -------------
2024-01-20 05:36:56,775 [INFO] |Fantasy Bot|
2024-01-20 05:36:56,775 [INFO] -------------
2024-01-20 05:37:35,386 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0925772e90>
2024-01-20 05:37:37,938 [DEBUG] Using selector: EpollSelector
2024-01-20 05:37:37,939 [INFO] logging in using static token
2024-01-20 05:37:39,046 [INFO] Shard ID 0 has connected to Gateway (Session ID: aa6bc4a17ebee6eeda7b9bf9e8b3fae7).
2024-01-20 05:37:41,055 [INFO] -------------
2024-01-20 05:37:41,055 [INFO] |Fantasy Bot|
2024-01-20 05:37:41,055 [INFO] -------------
2024-01-20 05:38:15,956 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f7e6c9abd30>
2024-01-20 05:38:19,306 [DEBUG] Using selector: EpollSelector
2024-01-20 05:38:19,308 [INFO] logging in using static token
2024-01-20 05:38:20,483 [INFO] Shard ID 0 has connected to Gateway (Session ID: a553f36bca2405d167d7daa37c7868b3).
2024-01-20 05:38:22,495 [INFO] -------------
2024-01-20 05:38:22,495 [INFO] |Fantasy Bot|
2024-01-20 05:38:22,496 [INFO] -------------
2024-01-20 05:38:47,979 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f653a60ee00>
2024-01-20 05:48:30,010 [DEBUG] Using selector: EpollSelector
2024-01-20 05:48:30,011 [INFO] logging in using static token
2024-01-20 05:48:31,100 [INFO] Shard ID 0 has connected to Gateway (Session ID: 42f7ae59aaf22ce1348c021afd4c5600).
2024-01-20 05:48:33,116 [INFO] -------------
2024-01-20 05:48:33,116 [INFO] |Fantasy Bot|
2024-01-20 05:48:33,117 [INFO] -------------
2024-01-20 05:49:59,335 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe62e0deef0>
2024-01-20 07:00:48,280 [DEBUG] Using selector: EpollSelector
2024-01-20 07:00:48,281 [INFO] logging in using static token
2024-01-20 07:00:50,720 [INFO] Shard ID 0 has connected to Gateway (Session ID: 742ec6546256225268078adb0f911ef2).
2024-01-20 07:00:52,734 [INFO] -------------
2024-01-20 07:00:52,735 [INFO] |Fantasy Bot|
2024-01-20 07:00:52,735 [INFO] -------------
2024-01-20 07:01:12,306 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 84, in on_message
    current_datetime = datetime.datetime.now().strftime("%Y%m%d%H%M")
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2024-01-20 07:01:26,072 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff679302dd0>
2024-01-20 07:01:29,022 [DEBUG] Using selector: EpollSelector
2024-01-20 07:01:29,023 [INFO] logging in using static token
2024-01-20 07:01:30,140 [INFO] Shard ID 0 has connected to Gateway (Session ID: f4a192e068ebdee6190eca6685793c9f).
2024-01-20 07:01:32,149 [INFO] -------------
2024-01-20 07:01:32,150 [INFO] |Fantasy Bot|
2024-01-20 07:01:32,150 [INFO] -------------
2024-01-21 06:22:02,628 [DEBUG] Using selector: EpollSelector
2024-01-21 06:22:02,630 [INFO] logging in using static token
2024-01-21 06:22:03,691 [INFO] Shard ID 0 has connected to Gateway (Session ID: b526e4fd456175bd13f2c395df03ddf5).
2024-01-21 06:22:05,698 [INFO] -------------
2024-01-21 06:22:05,698 [INFO] |Fantasy Bot|
2024-01-21 06:22:05,699 [INFO] -------------
2024-01-21 06:25:46,280 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2f7afceec0>
2024-01-21 07:30:57,771 [DEBUG] Using selector: EpollSelector
2024-01-21 07:30:57,774 [INFO] logging in using static token
2024-01-21 07:30:58,865 [INFO] Shard ID 0 has connected to Gateway (Session ID: 84f277576622d72e7b79c5b5720cf416).
2024-01-21 07:31:00,886 [INFO] -------------
2024-01-21 07:31:00,887 [INFO] |Fantasy Bot|
2024-01-21 07:31:00,887 [INFO] -------------
2024-01-21 07:31:36,673 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fdb646d2b60>
2024-01-21 07:32:12,116 [DEBUG] Using selector: EpollSelector
2024-01-21 07:32:12,118 [INFO] logging in using static token
2024-01-21 07:32:13,369 [INFO] Shard ID 0 has connected to Gateway (Session ID: 198b804f02964eb4d528593044eec108).
2024-01-21 07:32:15,374 [INFO] -------------
2024-01-21 07:32:15,375 [INFO] |Fantasy Bot|
2024-01-21 07:32:15,375 [INFO] -------------
2024-01-21 08:32:40,446 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9320332e00>
2024-01-21 21:20:13,408 [DEBUG] Using selector: EpollSelector
2024-01-21 21:20:13,409 [INFO] logging in using static token
2024-01-21 21:20:14,726 [INFO] Shard ID 0 has connected to Gateway (Session ID: 05971f498c17845c4b2dea579a2a844f).
2024-01-21 21:20:16,734 [INFO] -------------
2024-01-21 21:20:16,735 [INFO] |Fantasy Bot|
2024-01-21 21:20:16,735 [INFO] -------------
2024-01-21 21:20:28,645 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 72, in on_message
    query = cursor.execute("""
sqlite3.OperationalError: no such table: closed_game_teams
2024-01-21 21:20:51,837 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 72, in on_message
    query = cursor.execute("""
sqlite3.OperationalError: no such table: closed_game_teams
2024-01-21 21:21:21,370 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fada08af370>
2024-01-21 21:22:03,157 [DEBUG] Using selector: EpollSelector
2024-01-21 21:22:03,158 [INFO] logging in using static token
2024-01-21 21:22:04,223 [INFO] Shard ID 0 has connected to Gateway (Session ID: 42e13c448373619a0edf46a629a80205).
2024-01-21 21:22:06,230 [INFO] -------------
2024-01-21 21:22:06,231 [INFO] |Fantasy Bot|
2024-01-21 21:22:06,231 [INFO] -------------
2024-01-21 21:22:12,562 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 939, in _finalize_columns_and_data
    columns = _validate_or_indexify_columns(contents, columns)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 986, in _validate_or_indexify_columns
    raise AssertionError(
AssertionError: 1 columns passed, passed data had 2 columns

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 81, in on_message
    df = pd.DataFrame(data, columns=columns)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 809, in __init__
    arrays, columns, index = nested_data_to_arrays(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 520, in nested_data_to_arrays
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 845, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 942, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 1 columns passed, passed data had 2 columns
2024-01-21 21:22:28,123 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe44b8b7340>
2024-01-21 21:22:30,866 [DEBUG] Using selector: EpollSelector
2024-01-21 21:22:30,867 [INFO] logging in using static token
2024-01-21 21:22:32,058 [INFO] Shard ID 0 has connected to Gateway (Session ID: 42893efdc39a239fef3f94fe60cec484).
2024-01-21 21:22:43,512 [DEBUG] Using selector: EpollSelector
2024-01-21 21:22:43,512 [INFO] logging in using static token
2024-01-21 21:22:44,641 [INFO] Shard ID 0 has connected to Gateway (Session ID: 6b97e209dd7862c957243eed11b5dccb).
2024-01-21 21:22:46,658 [INFO] -------------
2024-01-21 21:22:46,658 [INFO] |Fantasy Bot|
2024-01-21 21:22:46,658 [INFO] -------------
2024-01-21 21:23:05,489 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 80, in on_message
    embed = discord.Embed(title=f"{message.author.name}'s team: ", color=self.generate_random_color())
AttributeError: 'fantasyBotBackend' object has no attribute 'generate_random_color'
2024-01-21 21:23:57,690 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f642c0ab310>
2024-01-21 21:24:00,977 [DEBUG] Using selector: EpollSelector
2024-01-21 21:24:00,978 [INFO] logging in using static token
2024-01-21 21:24:02,883 [INFO] Shard ID 0 has connected to Gateway (Session ID: ec31a02ff79bc2824d1736612c990ae6).
2024-01-21 21:24:04,889 [INFO] -------------
2024-01-21 21:24:04,890 [INFO] |Fantasy Bot|
2024-01-21 21:24:04,890 [INFO] -------------
2024-01-21 21:24:22,228 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff8830532e0>
2024-01-21 21:24:50,898 [DEBUG] Using selector: EpollSelector
2024-01-21 21:24:50,900 [INFO] logging in using static token
2024-01-21 21:24:52,108 [INFO] Shard ID 0 has connected to Gateway (Session ID: 687f76ca34c27177092acfc8d41ec229).
2024-01-21 21:24:54,116 [INFO] -------------
2024-01-21 21:24:54,116 [INFO] |Fantasy Bot|
2024-01-21 21:24:54,116 [INFO] -------------
2024-01-21 21:25:08,140 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3bf1363370>
2024-01-21 21:30:50,157 [DEBUG] Using selector: EpollSelector
2024-01-21 21:30:50,158 [INFO] logging in using static token
2024-01-21 21:30:51,253 [INFO] Shard ID 0 has connected to Gateway (Session ID: 8a4e14d532ae6154ee86d2fb78db9c53).
2024-01-21 21:30:53,278 [INFO] -------------
2024-01-21 21:30:53,278 [INFO] |Fantasy Bot|
2024-01-21 21:30:53,279 [INFO] -------------
2024-01-21 21:31:05,511 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 85, in on_message
    query = cursor.execute("""SELECT p.player_id, p.player_name, p.player_team, p.role, SUM(pdp.total_points) AS max_daily_score
sqlite3.OperationalError: no such column: p.player_team
2024-01-21 21:31:13,601 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb82c593310>
2024-01-21 21:31:56,866 [DEBUG] Using selector: EpollSelector
2024-01-21 21:31:56,866 [INFO] logging in using static token
2024-01-21 21:31:57,992 [INFO] Shard ID 0 has connected to Gateway (Session ID: f129eb837adf92e3f7cba00cdcaa1648).
2024-01-21 21:31:59,997 [INFO] -------------
2024-01-21 21:31:59,998 [INFO] |Fantasy Bot|
2024-01-21 21:31:59,998 [INFO] -------------
2024-01-21 21:32:20,573 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 85, in on_message
    query = cursor.execute("""SELECT p.player_id, p.player_name, p.team, p.role, SUM(pdp.total_points) AS max_daily_score
sqlite3.OperationalError: no such column: p.team
2024-01-21 21:32:38,197 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f89271273d0>
2024-01-21 21:32:40,818 [DEBUG] Using selector: EpollSelector
2024-01-21 21:32:40,819 [INFO] logging in using static token
2024-01-21 21:32:42,095 [INFO] Shard ID 0 has connected to Gateway (Session ID: 9daf20f7b4b2d0ffe955e51c731119dc).
2024-01-21 21:32:44,100 [INFO] -------------
2024-01-21 21:32:44,101 [INFO] |Fantasy Bot|
2024-01-21 21:32:44,101 [INFO] -------------
2024-01-21 21:32:46,993 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 85, in on_message
    query = cursor.execute("""SELECT p.player_id, p.player_name, p.team, p.role, SUM(pdp.total_points) AS max_daily_score
sqlite3.OperationalError: no such column: p.team
2024-01-21 21:32:53,848 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6ecf45b2b0>
2024-01-21 21:32:56,397 [DEBUG] Using selector: EpollSelector
2024-01-21 21:32:56,398 [INFO] logging in using static token
2024-01-21 21:32:57,627 [INFO] Shard ID 0 has connected to Gateway (Session ID: 685beb24decaa4fe51b8f7f7d0812fbc).
2024-01-21 21:32:59,635 [INFO] -------------
2024-01-21 21:32:59,635 [INFO] |Fantasy Bot|
2024-01-21 21:32:59,635 [INFO] -------------
2024-01-21 21:33:02,586 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 102, in on_message
    await message.channel.send(embed=embed)
  File "/usr/local/lib/python3.10/dist-packages/discord/abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
  File "/usr/local/lib/python3.10/dist-packages/discord/http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.value: Must be 1024 or fewer in length.
2024-01-21 21:33:09,396 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f8f2b9b72e0>
2024-01-21 21:33:11,972 [DEBUG] Using selector: EpollSelector
2024-01-21 21:33:11,973 [INFO] logging in using static token
2024-01-21 21:33:14,238 [INFO] Shard ID 0 has connected to Gateway (Session ID: ea15405bf08ad5770dd7300db8c60c2e).
2024-01-21 21:33:16,247 [INFO] -------------
2024-01-21 21:33:16,247 [INFO] |Fantasy Bot|
2024-01-21 21:33:16,247 [INFO] -------------
2024-01-21 21:34:25,334 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3261cff340>
2024-01-21 21:35:00,389 [DEBUG] Using selector: EpollSelector
2024-01-21 21:35:00,390 [INFO] logging in using static token
2024-01-21 21:35:11,349 [DEBUG] Using selector: EpollSelector
2024-01-21 21:35:11,349 [INFO] logging in using static token
2024-01-21 21:35:12,650 [INFO] Shard ID 0 has connected to Gateway (Session ID: 507c677c81b67e903242d27fa10ef7fd).
2024-01-21 21:35:14,657 [INFO] -------------
2024-01-21 21:35:14,658 [INFO] |Fantasy Bot|
2024-01-21 21:35:14,658 [INFO] -------------
2024-01-21 21:35:15,085 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f838efa7340>
2024-01-21 21:35:27,101 [DEBUG] Using selector: EpollSelector
2024-01-21 21:35:27,101 [INFO] logging in using static token
2024-01-21 21:35:28,159 [INFO] Shard ID 0 has connected to Gateway (Session ID: cb1c42ce5175e63acabfba2a3c63b364).
2024-01-21 21:35:30,167 [INFO] -------------
2024-01-21 21:35:30,168 [INFO] |Fantasy Bot|
2024-01-21 21:35:30,168 [INFO] -------------
2024-01-21 21:35:36,656 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 939, in _finalize_columns_and_data
    columns = _validate_or_indexify_columns(contents, columns)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 986, in _validate_or_indexify_columns
    raise AssertionError(
AssertionError: 4 columns passed, passed data had 5 columns

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 97, in on_message
    df = pd.DataFrame(data, columns=columns)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 809, in __init__
    arrays, columns, index = nested_data_to_arrays(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 520, in nested_data_to_arrays
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 845, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/internals/construction.py", line 942, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 4 columns passed, passed data had 5 columns
2024-01-21 21:36:25,270 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff13a0cb370>
2024-01-21 21:36:27,746 [DEBUG] Using selector: EpollSelector
2024-01-21 21:36:27,746 [INFO] logging in using static token
2024-01-21 21:36:28,845 [INFO] Shard ID 0 has connected to Gateway (Session ID: d81422e6f894e5353e872f7548db67ab).
2024-01-21 21:36:30,850 [INFO] -------------
2024-01-21 21:36:30,851 [INFO] |Fantasy Bot|
2024-01-21 21:36:30,851 [INFO] -------------
2024-01-21 21:36:31,466 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 98, in on_message
    support_df = df.filter('Role' == 'support').head(5)[['Player ID', 'Player Name', 'Team Name', 'Total Score']]
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5704, in filter
    items = Index(items).intersection(labels)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 524, in __new__
    raise cls._raise_scalar_data_error(data)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5265, in _raise_scalar_data_error
    raise TypeError(
TypeError: Index(...) must be called with a collection of some kind, False was passed
2024-01-21 21:37:18,814 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f916b6ff250>
2024-01-21 21:37:21,625 [DEBUG] Using selector: EpollSelector
2024-01-21 21:37:21,625 [INFO] logging in using static token
2024-01-21 21:37:22,733 [INFO] Shard ID 0 has connected to Gateway (Session ID: 1f19ce67d2643719f5468947c5f13863).
2024-01-21 21:37:24,739 [INFO] -------------
2024-01-21 21:37:24,739 [INFO] |Fantasy Bot|
2024-01-21 21:37:24,739 [INFO] -------------
2024-01-21 21:37:32,567 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 98, in on_message
    support_df = df.filter('Role' == 'support').head(5)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5704, in filter
    items = Index(items).intersection(labels)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 524, in __new__
    raise cls._raise_scalar_data_error(data)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5265, in _raise_scalar_data_error
    raise TypeError(
TypeError: Index(...) must be called with a collection of some kind, False was passed
2024-01-21 21:38:33,277 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2f4d7bb3a0>
2024-01-21 21:38:35,727 [DEBUG] Using selector: EpollSelector
2024-01-21 21:38:35,727 [INFO] logging in using static token
2024-01-21 21:38:36,837 [INFO] Shard ID 0 has connected to Gateway (Session ID: ea1fc541952c4ed0b4b4d01797010957).
2024-01-21 21:38:38,845 [INFO] -------------
2024-01-21 21:38:38,845 [INFO] |Fantasy Bot|
2024-01-21 21:38:38,845 [INFO] -------------
2024-01-21 21:38:45,594 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 98, in on_message
    support_df = df.filter('Role' == 'support')
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 5704, in filter
    items = Index(items).intersection(labels)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 524, in __new__
    raise cls._raise_scalar_data_error(data)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 5265, in _raise_scalar_data_error
    raise TypeError(
TypeError: Index(...) must be called with a collection of some kind, False was passed
2024-01-21 21:39:18,509 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f7b50693340>
2024-01-21 21:39:20,948 [DEBUG] Using selector: EpollSelector
2024-01-21 21:39:20,949 [INFO] logging in using static token
2024-01-21 21:39:22,007 [INFO] Shard ID 0 has connected to Gateway (Session ID: 77968ca103a7e7e7422133edeb99af12).
2024-01-21 21:39:24,015 [INFO] -------------
2024-01-21 21:39:24,015 [INFO] |Fantasy Bot|
2024-01-21 21:39:24,015 [INFO] -------------
2024-01-21 21:40:00,124 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f679c4ff370>
2024-01-21 21:40:17,710 [DEBUG] Using selector: EpollSelector
2024-01-21 21:40:17,710 [INFO] logging in using static token
2024-01-21 21:40:18,887 [INFO] Shard ID 0 has connected to Gateway (Session ID: 2f766e55ec5d1dfb04ecec6d3d144ebb).
2024-01-21 21:40:20,894 [INFO] -------------
2024-01-21 21:40:20,894 [INFO] |Fantasy Bot|
2024-01-21 21:40:20,895 [INFO] -------------
2024-01-21 21:40:46,092 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f768dec3340>
2024-01-21 21:40:48,495 [DEBUG] Using selector: EpollSelector
2024-01-21 21:40:48,496 [INFO] logging in using static token
2024-01-21 21:40:49,896 [INFO] Shard ID 0 has connected to Gateway (Session ID: 6ae09e796f3110961e867269b4e31b19).
2024-01-21 21:40:51,906 [INFO] -------------
2024-01-21 21:40:51,907 [INFO] |Fantasy Bot|
2024-01-21 21:40:51,907 [INFO] -------------
2024-01-21 21:41:01,469 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7febc58eb220>
2024-01-21 21:41:04,539 [DEBUG] Using selector: EpollSelector
2024-01-21 21:41:04,539 [INFO] logging in using static token
2024-01-21 21:41:05,815 [INFO] Shard ID 0 has connected to Gateway (Session ID: 599743def7bc5385e8a0b0219af01fbf).
2024-01-21 21:41:07,822 [INFO] -------------
2024-01-21 21:41:07,823 [INFO] |Fantasy Bot|
2024-01-21 21:41:07,823 [INFO] -------------
2024-01-21 21:41:22,482 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f4b1ff773d0>
2024-01-21 21:43:45,982 [DEBUG] Using selector: EpollSelector
2024-01-21 21:43:45,983 [INFO] logging in using static token
2024-01-21 21:43:47,988 [INFO] Shard ID 0 has connected to Gateway (Session ID: e4133d28028f7345b22e42d9a0151964).
2024-01-21 21:43:49,995 [INFO] -------------
2024-01-21 21:43:49,995 [INFO] |Fantasy Bot|
2024-01-21 21:43:49,995 [INFO] -------------
2024-01-21 21:45:51,331 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f14b18e32e0>
2024-01-21 21:46:01,214 [DEBUG] Using selector: EpollSelector
2024-01-21 21:46:01,214 [INFO] logging in using static token
2024-01-21 21:46:02,417 [INFO] Shard ID 0 has connected to Gateway (Session ID: 2b4fbfd4713a764bc322f6be5fe61654).
2024-01-21 21:46:04,425 [INFO] -------------
2024-01-21 21:46:04,425 [INFO] |Fantasy Bot|
2024-01-21 21:46:04,426 [INFO] -------------
2024-01-21 21:46:37,996 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb94b0431c0>
2024-01-21 21:46:40,493 [DEBUG] Using selector: EpollSelector
2024-01-21 21:46:40,494 [INFO] logging in using static token
2024-01-21 21:46:41,569 [INFO] Shard ID 0 has connected to Gateway (Session ID: b020c3d52bbdb8c8e74e67e097abeb35).
2024-01-21 21:46:43,576 [INFO] -------------
2024-01-21 21:46:43,576 [INFO] |Fantasy Bot|
2024-01-21 21:46:43,577 [INFO] -------------
2024-01-21 21:50:42,713 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f55888c3370>
2024-01-21 23:54:53,236 [DEBUG] Using selector: EpollSelector
2024-01-21 23:54:53,238 [INFO] logging in using static token
2024-01-21 23:54:54,410 [INFO] Shard ID 0 has connected to Gateway (Session ID: 113ba2abb8b87e4b48347b658abc2ccd).
2024-01-21 23:54:56,419 [INFO] -------------
2024-01-21 23:54:56,420 [INFO] |Fantasy Bot|
2024-01-21 23:54:56,420 [INFO] -------------
2024-01-21 23:55:25,968 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5338ddb250>
2024-01-21 23:59:18,623 [DEBUG] Using selector: EpollSelector
2024-01-21 23:59:18,624 [INFO] logging in using static token
2024-01-21 23:59:19,719 [INFO] Shard ID 0 has connected to Gateway (Session ID: a62cd7f2f4ff74185e7c3f190a6ffb13).
2024-01-21 23:59:21,726 [INFO] -------------
2024-01-21 23:59:21,726 [INFO] |Fantasy Bot|
2024-01-21 23:59:21,726 [INFO] -------------
2024-01-21 23:59:38,024 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fdc9a63b3a0>
2024-01-22 01:07:44,455 [DEBUG] Using selector: EpollSelector
2024-01-22 01:07:44,457 [INFO] logging in using static token
2024-01-22 01:07:45,632 [INFO] Shard ID 0 has connected to Gateway (Session ID: c006b2708765f08ea51ad14c243288b6).
2024-01-22 01:07:47,657 [INFO] -------------
2024-01-22 01:07:47,658 [INFO] |Fantasy Bot|
2024-01-22 01:07:47,658 [INFO] -------------
2024-01-22 01:07:57,453 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 187, in on_message
    df = pd.DataFrame(data, columns=columns)
UnboundLocalError: local variable 'data' referenced before assignment
2024-01-22 01:08:27,538 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff286947400>
2024-01-22 01:08:32,137 [DEBUG] Using selector: EpollSelector
2024-01-22 01:08:32,138 [INFO] logging in using static token
2024-01-22 01:08:33,393 [INFO] Shard ID 0 has connected to Gateway (Session ID: 5d670621a68a2d2a0cdb4e793195f6db).
2024-01-22 01:08:35,401 [INFO] -------------
2024-01-22 01:08:35,402 [INFO] |Fantasy Bot|
2024-01-22 01:08:35,402 [INFO] -------------
2024-01-22 01:08:40,033 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 194, in on_message
    query = cursor.execute(f"""SELECT
sqlite3.OperationalError: incomplete input
2024-01-22 01:09:03,139 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f4b63ef3370>
2024-01-22 01:09:06,740 [DEBUG] Using selector: EpollSelector
2024-01-22 01:09:06,741 [INFO] logging in using static token
2024-01-22 01:09:07,892 [INFO] Shard ID 0 has connected to Gateway (Session ID: 76b8dc48cb649ab1d7822d0d80c0fcc8).
2024-01-22 01:09:09,925 [INFO] -------------
2024-01-22 01:09:09,925 [INFO] |Fantasy Bot|
2024-01-22 01:09:09,925 [INFO] -------------
2024-01-22 01:10:38,990 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3ce8bff370>
2024-01-22 01:12:04,429 [DEBUG] Using selector: EpollSelector
2024-01-22 01:12:04,429 [INFO] logging in using static token
2024-01-22 01:12:05,465 [INFO] Shard ID 0 has connected to Gateway (Session ID: 7c0ed2545674a78096f9705d9067ac7c).
2024-01-22 01:12:07,473 [INFO] -------------
2024-01-22 01:12:07,473 [INFO] |Fantasy Bot|
2024-01-22 01:12:07,474 [INFO] -------------
2024-01-22 01:13:14,691 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5f4305f3d0>
2024-01-22 01:13:25,513 [DEBUG] Using selector: EpollSelector
2024-01-22 01:13:25,515 [INFO] logging in using static token
2024-01-22 01:13:26,511 [INFO] Shard ID 0 has connected to Gateway (Session ID: 3d7e69e01b5464b2f7fec26229235992).
2024-01-22 01:13:28,520 [INFO] -------------
2024-01-22 01:13:28,520 [INFO] |Fantasy Bot|
2024-01-22 01:13:28,520 [INFO] -------------
2024-01-22 01:14:32,145 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f847ae43370>
2024-01-22 01:14:35,974 [DEBUG] Using selector: EpollSelector
2024-01-22 01:14:35,975 [INFO] logging in using static token
2024-01-22 01:14:37,303 [INFO] Shard ID 0 has connected to Gateway (Session ID: 464875dda79728ec8fe73acf93c44409).
2024-01-22 01:14:39,310 [INFO] -------------
2024-01-22 01:14:39,310 [INFO] |Fantasy Bot|
2024-01-22 01:14:39,311 [INFO] -------------
2024-01-22 01:14:42,794 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 208, in on_message
    embed = discord.Embed(title=f"Incoming trade requests: ", color=self.generate_random_color(), text="To accept trade, use +trade accept <trade_id>")
TypeError: Embed.__init__() got an unexpected keyword argument 'text'
2024-01-22 01:15:24,859 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f73345d33a0>
2024-01-22 01:15:33,833 [DEBUG] Using selector: EpollSelector
2024-01-22 01:15:33,834 [INFO] logging in using static token
2024-01-22 01:15:34,978 [INFO] Shard ID 0 has connected to Gateway (Session ID: 224afc1ebf0e2db6333d9138aa38f317).
2024-01-22 01:15:36,986 [INFO] -------------
2024-01-22 01:15:36,986 [INFO] |Fantasy Bot|
2024-01-22 01:15:36,986 [INFO] -------------
2024-01-22 01:15:41,521 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Fantasy Bot/fantasyBotBackend.py", line 208, in on_message
    embed = discord.Embed(title=f"Incoming trade requests: ", color=self.generate_random_color(), value="To accept trade, use +trade accept <trade_id>")
TypeError: Embed.__init__() got an unexpected keyword argument 'value'
2024-01-22 01:16:06,745 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd278c47400>
2024-01-22 01:16:09,178 [DEBUG] Using selector: EpollSelector
2024-01-22 01:16:09,179 [INFO] logging in using static token
2024-01-22 01:16:10,250 [INFO] Shard ID 0 has connected to Gateway (Session ID: e8a43ee9b67882f785f9c8c29a069203).
2024-01-22 01:16:12,264 [INFO] -------------
2024-01-22 01:16:12,264 [INFO] |Fantasy Bot|
2024-01-22 01:16:12,264 [INFO] -------------
2024-01-22 01:17:11,686 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f13de0c7280>
2024-01-22 01:17:33,402 [DEBUG] Using selector: EpollSelector
2024-01-22 01:17:33,403 [INFO] logging in using static token
2024-01-22 01:17:34,450 [INFO] Shard ID 0 has connected to Gateway (Session ID: c2298c0819df636d59e6446a998c34c4).
2024-01-22 01:17:36,466 [INFO] -------------
2024-01-22 01:17:36,466 [INFO] |Fantasy Bot|
2024-01-22 01:17:36,466 [INFO] -------------
2024-01-22 01:19:54,477 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f249066f3a0>
2024-01-21 19:04:56,325 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:04:56,327 [INFO] logging in using static token
2024-01-21 19:04:57,429 [INFO] Shard ID 0 has connected to Gateway (Session ID: 337def8b7c5acb99cf5c046a798f74ad).
2024-01-21 19:04:59,441 [INFO] -------------
2024-01-21 19:04:59,441 [INFO] |Fantasy Bot|
2024-01-21 19:04:59,441 [INFO] -------------
2024-01-21 19:05:26,471 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 221, in on_message
    query = cursor.execute(f"""SELECT
            ^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: p.is_active
2024-01-21 19:05:31,204 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001C045E56030>
2024-01-21 19:06:20,341 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:06:20,342 [INFO] logging in using static token
2024-01-21 19:06:21,486 [INFO] Shard ID 0 has connected to Gateway (Session ID: 8618fa2799d72a385d5b7505bff8b175).
2024-01-21 19:06:23,496 [INFO] -------------
2024-01-21 19:06:23,496 [INFO] |Fantasy Bot|
2024-01-21 19:06:23,496 [INFO] -------------
2024-01-21 19:06:41,853 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 222, in on_message
    query = cursor.execute(f"""SELECT
            ^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near ".": syntax error
2024-01-21 19:06:46,226 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022F80420620>
2024-01-21 19:07:09,790 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:07:09,791 [INFO] logging in using static token
2024-01-21 19:07:11,035 [INFO] Shard ID 0 has connected to Gateway (Session ID: e6f43ec070e115bc5ef567511e2127c6).
2024-01-21 19:07:13,038 [INFO] -------------
2024-01-21 19:07:13,038 [INFO] |Fantasy Bot|
2024-01-21 19:07:13,038 [INFO] -------------
2024-01-21 19:07:15,294 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001BEEBAD5CD0>
2024-01-21 19:07:36,821 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:07:36,822 [INFO] logging in using static token
2024-01-21 19:07:38,014 [INFO] Shard ID 0 has connected to Gateway (Session ID: 360a25e0ebe10223b8dba1f0d23490a6).
2024-01-21 19:07:40,036 [INFO] -------------
2024-01-21 19:07:40,036 [INFO] |Fantasy Bot|
2024-01-21 19:07:40,036 [INFO] -------------
2024-01-21 19:08:41,526 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000169A5AE01A0>
2024-01-21 19:09:01,641 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:09:01,642 [INFO] logging in using static token
2024-01-21 19:09:02,684 [INFO] Shard ID 0 has connected to Gateway (Session ID: 33eb9ec1cc74e1110a1f3ab7ff4b491c).
2024-01-21 19:09:04,688 [INFO] -------------
2024-01-21 19:09:04,689 [INFO] |Fantasy Bot|
2024-01-21 19:09:04,689 [INFO] -------------
2024-01-21 19:09:20,572 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 939, in _finalize_columns_and_data
    columns = _validate_or_indexify_columns(contents, columns)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 986, in _validate_or_indexify_columns
    raise AssertionError(
AssertionError: 5 columns passed, passed data had 6 columns

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 234, in on_message
    df = pd.DataFrame(data, columns=columns)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\frame.py", line 840, in __init__
    arrays, columns, index = nested_data_to_arrays(
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 520, in nested_data_to_arrays
    arrays, columns = to_arrays(data, columns, dtype=dtype)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 845, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 942, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 5 columns passed, passed data had 6 columns
2024-01-21 19:09:36,761 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022C01FADC10>
2024-01-21 19:09:39,867 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:09:39,869 [INFO] logging in using static token
2024-01-21 19:09:41,082 [INFO] Shard ID 0 has connected to Gateway (Session ID: aac96e655e65af3c1ae9d64d00c02402).
2024-01-21 19:09:43,083 [INFO] -------------
2024-01-21 19:09:43,083 [INFO] |Fantasy Bot|
2024-01-21 19:09:43,083 [INFO] -------------
2024-01-21 19:09:50,200 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 153, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 182, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'eliminated'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 234, in on_message
    df['eliminated'] = df['eliminated'].map({1: True, 0: False})
                       ~~^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\indexes\base.py", line 3809, in get_loc
    raise KeyError(key) from err
KeyError: 'eliminated'
2024-01-21 19:09:54,225 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001923DADAAE0>
2024-01-21 19:10:11,583 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:10:11,585 [INFO] logging in using static token
2024-01-21 19:10:12,587 [INFO] Shard ID 0 has connected to Gateway (Session ID: 3968c0443359c7606835a654dbbb56e0).
2024-01-21 19:10:14,600 [INFO] -------------
2024-01-21 19:10:14,600 [INFO] |Fantasy Bot|
2024-01-21 19:10:14,600 [INFO] -------------
2024-01-21 19:18:41,918 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001EA9F058260>
2024-01-21 19:24:42,702 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:24:42,703 [INFO] logging in using static token
2024-01-21 19:24:43,822 [INFO] Shard ID 0 has connected to Gateway (Session ID: d434e2a0002629fc7b26c09bbe329dda).
2024-01-21 19:24:45,826 [INFO] -------------
2024-01-21 19:24:45,826 [INFO] |Fantasy Bot|
2024-01-21 19:24:45,826 [INFO] -------------
2024-01-21 19:25:41,243 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000199628D4260>
2024-01-21 19:25:44,215 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:25:44,216 [INFO] logging in using static token
2024-01-21 19:25:45,283 [INFO] Shard ID 0 has connected to Gateway (Session ID: 05f61f88de66ed510ae23f5a5ae4720f).
2024-01-21 19:25:47,292 [INFO] -------------
2024-01-21 19:25:47,292 [INFO] |Fantasy Bot|
2024-01-21 19:25:47,292 [INFO] -------------
2024-01-21 19:25:58,161 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002593C206BD0>
2024-01-21 19:26:00,931 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:26:00,932 [INFO] logging in using static token
2024-01-21 19:26:02,095 [INFO] Shard ID 0 has connected to Gateway (Session ID: c001b107811303e178569991303a8840).
2024-01-21 19:26:04,106 [INFO] -------------
2024-01-21 19:26:04,106 [INFO] |Fantasy Bot|
2024-01-21 19:26:04,106 [INFO] -------------
2024-01-21 19:27:36,745 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002327FB44C20>
2024-01-21 19:28:24,018 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:28:24,019 [INFO] logging in using static token
2024-01-21 19:28:25,100 [INFO] Shard ID 0 has connected to Gateway (Session ID: 3b7b186093bb759026308d7001b3028a).
2024-01-21 19:28:27,120 [INFO] -------------
2024-01-21 19:28:27,121 [INFO] |Fantasy Bot|
2024-01-21 19:28:27,121 [INFO] -------------
2024-01-21 19:30:29,361 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000283DCC714C0>
2024-01-21 19:31:03,969 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:31:03,970 [INFO] logging in using static token
2024-01-21 19:31:05,076 [INFO] Shard ID 0 has connected to Gateway (Session ID: 8d47e6ba04e3f4747efd19c8dbe1ea6b).
2024-01-21 19:31:07,098 [INFO] -------------
2024-01-21 19:31:07,098 [INFO] |Fantasy Bot|
2024-01-21 19:31:07,098 [INFO] -------------
2024-01-21 19:31:07,339 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 262, in on_message
    query = cursor.execute(f"""SELECT player_id FROM players WHERE requestedplayerid = '{requestedplayerid}'""")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: requestedplayerid
2024-01-21 19:31:18,387 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000286E41FBA10>
2024-01-21 19:31:21,645 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:31:21,646 [INFO] logging in using static token
2024-01-21 19:31:22,740 [INFO] Shard ID 0 has connected to Gateway (Session ID: bf2218ab49c431f8c8621641e79fed9f).
2024-01-21 19:31:24,757 [INFO] -------------
2024-01-21 19:31:24,757 [INFO] |Fantasy Bot|
2024-01-21 19:31:24,757 [INFO] -------------
2024-01-21 19:34:11,642 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022F3D4C8500>
2024-01-21 19:34:35,067 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:34:35,068 [INFO] logging in using static token
2024-01-21 19:34:36,182 [INFO] Shard ID 0 has connected to Gateway (Session ID: 67fd72b2882acd10b10a1e134d899bd6).
2024-01-21 19:34:38,212 [INFO] -------------
2024-01-21 19:34:38,212 [INFO] |Fantasy Bot|
2024-01-21 19:34:38,212 [INFO] -------------
2024-01-21 19:35:01,544 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D7E98740B0>
2024-01-21 19:35:48,327 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:35:48,328 [INFO] logging in using static token
2024-01-21 19:35:49,334 [INFO] Shard ID 0 has connected to Gateway (Session ID: 92d1a4885777e9fef860844c0d533080).
2024-01-21 19:35:51,351 [INFO] -------------
2024-01-21 19:35:51,351 [INFO] |Fantasy Bot|
2024-01-21 19:35:51,351 [INFO] -------------
2024-01-21 19:35:53,999 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 271, in on_message
    requestee_name = data[1]
                     ~~~~^^^
IndexError: tuple index out of range
2024-01-21 19:36:04,853 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002C36D6D4170>
2024-01-21 19:36:07,920 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:36:07,922 [INFO] logging in using static token
2024-01-21 19:36:09,056 [INFO] Shard ID 0 has connected to Gateway (Session ID: 6b84981f689e2bf06c895e0edf099ac5).
2024-01-21 19:36:11,066 [INFO] -------------
2024-01-21 19:36:11,067 [INFO] |Fantasy Bot|
2024-01-21 19:36:11,067 [INFO] -------------
2024-01-21 19:36:12,392 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 273, in on_message
    requestee_name = data[1]
                     ~~~~^^^
IndexError: tuple index out of range
2024-01-21 19:37:16,246 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000014458358230>
2024-01-21 19:37:23,012 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:37:23,013 [INFO] logging in using static token
2024-01-21 19:37:24,082 [INFO] Shard ID 0 has connected to Gateway (Session ID: 7052bd06b36fcae41afeee6f36282923).
2024-01-21 19:37:26,088 [INFO] -------------
2024-01-21 19:37:26,088 [INFO] |Fantasy Bot|
2024-01-21 19:37:26,088 [INFO] -------------
2024-01-21 19:39:52,992 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000023657576630>
2024-01-21 19:41:44,081 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:41:44,081 [INFO] logging in using static token
2024-01-21 19:41:45,288 [INFO] Shard ID 0 has connected to Gateway (Session ID: 43b9b930680ee5c87c6e5d2f59339b80).
2024-01-21 19:41:47,301 [INFO] -------------
2024-01-21 19:41:47,301 [INFO] |Fantasy Bot|
2024-01-21 19:41:47,301 [INFO] -------------
2024-01-21 19:41:58,443 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 246, in on_message
    myplayerid, requestedplayerid = parse_trade_request(message.content)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
2024-01-21 19:42:59,876 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022E9A2D24B0>
2024-01-21 19:50:23,994 [DEBUG] Using proactor: IocpProactor
2024-01-21 19:50:23,995 [INFO] logging in using static token
2024-01-21 19:50:25,291 [INFO] Shard ID 0 has connected to Gateway (Session ID: 6e817e8ea246dffe1702dfe08c361b0e).
2024-01-21 19:50:27,332 [INFO] -------------
2024-01-21 19:50:27,332 [INFO] |Fantasy Bot|
2024-01-21 19:50:27,332 [INFO] -------------
2024-01-21 19:52:00,384 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024E351AEED0>
2024-01-21 22:37:56,178 [DEBUG] Using proactor: IocpProactor
2024-01-21 22:37:56,182 [INFO] logging in using static token
2024-01-21 22:37:57,376 [INFO] Shard ID 0 has connected to Gateway (Session ID: 5cab026bad2b009f667b4b3b43b5eac3).
2024-01-21 22:37:59,387 [INFO] -------------
2024-01-21 22:37:59,387 [INFO] |Fantasy Bot|
2024-01-21 22:37:59,387 [INFO] -------------
2024-01-21 22:38:24,402 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 304, in on_message
    cursor.execute(f"""UPDATE closed_game_teams SET is_action = False
sqlite3.OperationalError: no such column: is_action
2024-01-21 22:38:59,543 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DAA0B13320>
2024-01-21 22:39:24,658 [DEBUG] Using proactor: IocpProactor
2024-01-21 22:39:24,660 [INFO] logging in using static token
2024-01-21 22:39:25,686 [INFO] Shard ID 0 has connected to Gateway (Session ID: 7b4a546516d3d6ab6eb03788f5acd115).
2024-01-21 22:39:27,690 [INFO] -------------
2024-01-21 22:39:27,690 [INFO] |Fantasy Bot|
2024-01-21 22:39:27,690 [INFO] -------------
2024-01-21 22:39:58,874 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000175D3CAE030>
2024-01-21 22:41:53,032 [DEBUG] Using proactor: IocpProactor
2024-01-21 22:41:53,033 [INFO] logging in using static token
2024-01-21 22:41:54,177 [INFO] Shard ID 0 has connected to Gateway (Session ID: 57562ea3786f7da25e581df21451925a).
2024-01-21 22:41:56,181 [INFO] -------------
2024-01-21 22:41:56,181 [INFO] |Fantasy Bot|
2024-01-21 22:41:56,181 [INFO] -------------
2024-01-21 22:43:24,046 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 292, in on_message
    cursor.execute(f"""UPDATE closed_game_teams SET is_action = False WHERE player_id = {requester_player_id} and manager_id = {manager_id}""")
sqlite3.OperationalError: no such column: is_action
2024-01-21 22:44:47,238 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020846532BA0>
2024-01-21 22:44:59,922 [DEBUG] Using proactor: IocpProactor
2024-01-21 22:44:59,923 [INFO] logging in using static token
2024-01-21 22:45:01,021 [INFO] Shard ID 0 has connected to Gateway (Session ID: b52acb75c12768b6e7494002c616b083).
2024-01-21 22:45:03,041 [INFO] -------------
2024-01-21 22:45:03,041 [INFO] |Fantasy Bot|
2024-01-21 22:45:03,041 [INFO] -------------
2024-01-21 22:48:27,868 [INFO] Shard ID 0 has successfully RESUMED session b52acb75c12768b6e7494002c616b083.
2024-01-21 22:48:31,901 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002573837DBB0>
2024-01-21 22:53:29,802 [DEBUG] Using proactor: IocpProactor
2024-01-21 22:53:29,802 [INFO] logging in using static token
2024-01-21 22:53:30,834 [INFO] Shard ID 0 has connected to Gateway (Session ID: bf42365d1ab9bf7fee63fdc91dcf5aa2).
2024-01-21 22:53:32,849 [INFO] -------------
2024-01-21 22:53:32,849 [INFO] |Fantasy Bot|
2024-01-21 22:53:32,849 [INFO] -------------
2024-01-21 22:56:36,447 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 87, in on_message
    await message.channel.send(embed=embed)
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.value: Must be 1024 or fewer in length.
2024-01-21 22:56:58,930 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 87, in on_message
    await message.channel.send(embed=embed)
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\abc.py", line 1561, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\http.py", line 745, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.value: Must be 1024 or fewer in length.
2024-01-21 22:58:14,237 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000022E1217CB60>
2024-01-21 22:58:22,265 [DEBUG] Using proactor: IocpProactor
2024-01-21 22:58:22,267 [INFO] logging in using static token
2024-01-21 22:58:23,239 [INFO] Shard ID 0 has connected to Gateway (Session ID: e7f4b933ed293a101459d01d7896e88a).
2024-01-21 22:58:25,251 [INFO] -------------
2024-01-21 22:58:25,251 [INFO] |Fantasy Bot|
2024-01-21 22:58:25,251 [INFO] -------------
2024-01-21 22:59:19,897 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020B28946300>
2024-01-22 17:19:42,326 [DEBUG] Using proactor: IocpProactor
2024-01-22 17:19:42,331 [INFO] logging in using static token
2024-01-22 17:19:43,608 [INFO] Shard ID 0 has connected to Gateway (Session ID: d138c4214211cc10d872b8dd90e3dabf).
2024-01-22 17:19:45,634 [INFO] -------------
2024-01-22 17:19:45,634 [INFO] |Fantasy Bot|
2024-01-22 17:19:45,634 [INFO] -------------
2024-01-22 17:20:57,350 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 66, in on_message
    if closedCheck[0] == True:
       ~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-22 17:21:11,410 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 338, in on_message
    manager_id = data[0]
                 ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-22 17:21:47,499 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DA62442B70>
2024-01-22 17:22:13,447 [DEBUG] Using proactor: IocpProactor
2024-01-22 17:22:13,448 [INFO] logging in using static token
2024-01-22 17:22:14,622 [INFO] Shard ID 0 has connected to Gateway (Session ID: b202ffc6e72920f49f2b4ab551c6c998).
2024-01-22 17:22:16,636 [INFO] -------------
2024-01-22 17:22:16,636 [INFO] |Fantasy Bot|
2024-01-22 17:22:16,637 [INFO] -------------
2024-01-22 17:22:28,067 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 74, in on_message
    query = cursor.execute(f"""
            ^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: is_active
2024-01-22 17:25:31,706 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000013AB80D2060>
2024-01-22 17:25:47,024 [DEBUG] Using proactor: IocpProactor
2024-01-22 17:25:47,027 [INFO] logging in using static token
2024-01-22 17:25:48,286 [INFO] Shard ID 0 has connected to Gateway (Session ID: 017ca846919a2e617377f6d5fc18cd27).
2024-01-22 17:25:50,306 [INFO] -------------
2024-01-22 17:25:50,306 [INFO] |Fantasy Bot|
2024-01-22 17:25:50,307 [INFO] -------------
2024-01-22 17:25:57,519 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 344, in on_message
    player_id = data[0]
                ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-22 17:26:25,377 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001BBB88E07D0>
2024-01-22 17:26:43,519 [DEBUG] Using proactor: IocpProactor
2024-01-22 17:26:43,522 [INFO] logging in using static token
2024-01-22 17:26:44,776 [INFO] Shard ID 0 has connected to Gateway (Session ID: 83301a977be4638bd886516e26e21296).
2024-01-22 17:26:46,791 [INFO] -------------
2024-01-22 17:26:46,791 [INFO] |Fantasy Bot|
2024-01-22 17:26:46,791 [INFO] -------------
2024-01-22 17:29:31,096 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020C1B0C5BB0>
2024-01-22 17:43:46,121 [DEBUG] Using proactor: IocpProactor
2024-01-22 17:43:46,122 [INFO] logging in using static token
2024-01-22 17:43:47,240 [INFO] Shard ID 0 has connected to Gateway (Session ID: 8a389ce91585959745ce5d4786879d94).
2024-01-22 17:43:49,244 [INFO] -------------
2024-01-22 17:43:49,244 [INFO] |Fantasy Bot|
2024-01-22 17:43:49,244 [INFO] -------------
2024-01-22 17:46:42,238 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002292006DD30>
2024-01-23 18:05:51,697 [DEBUG] Using proactor: IocpProactor
2024-01-23 18:05:51,701 [INFO] logging in using static token
2024-01-23 18:05:52,853 [INFO] Shard ID 0 has connected to Gateway (Session ID: 96b211f3f238d78eaa8585c771a24054).
2024-01-23 18:05:53,776 [INFO] Message from axon319: +myscore
2024-01-23 18:05:53,793 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 939, in _finalize_columns_and_data
    columns = _validate_or_indexify_columns(contents, columns)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 986, in _validate_or_indexify_columns
    raise AssertionError(
AssertionError: 1 columns passed, passed data had 2 columns

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 125, in on_message
    df = pd.DataFrame(data, columns=columns)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\frame.py", line 840, in __init__
    arrays, columns, index = nested_data_to_arrays(
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 520, in nested_data_to_arrays
    arrays, columns = to_arrays(data, columns, dtype=dtype)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 845, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\internals\construction.py", line 942, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 1 columns passed, passed data had 2 columns
2024-01-23 18:05:54,884 [INFO] -------------
2024-01-23 18:05:54,884 [INFO] |Fantasy Bot|
2024-01-23 18:05:54,884 [INFO] -------------
2024-01-23 18:06:06,986 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000014B81071D00>
2024-01-23 18:06:10,308 [DEBUG] Using proactor: IocpProactor
2024-01-23 18:06:10,309 [INFO] logging in using static token
2024-01-23 18:06:11,279 [INFO] Shard ID 0 has connected to Gateway (Session ID: e269e703ebc21081311bbc07d4a3087b).
2024-01-23 18:06:13,319 [INFO] -------------
2024-01-23 18:06:13,319 [INFO] |Fantasy Bot|
2024-01-23 18:06:13,319 [INFO] -------------
2024-01-23 18:06:31,648 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001E4675EFFB0>
2024-01-23 18:06:35,222 [DEBUG] Using proactor: IocpProactor
2024-01-23 18:06:35,223 [INFO] logging in using static token
2024-01-23 18:06:36,253 [INFO] Shard ID 0 has connected to Gateway (Session ID: f3228a5f70ea2df60791e2121539a599).
2024-01-23 18:06:37,350 [INFO] Message from axon319: +myscore
2024-01-23 18:06:38,437 [INFO] -------------
2024-01-23 18:06:38,438 [INFO] |Fantasy Bot|
2024-01-23 18:06:38,438 [INFO] -------------
2024-01-23 18:08:43,827 [INFO] Message from axon319: +myscore
2024-01-23 18:10:24,897 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000199F695A210>
2024-01-23 18:10:32,838 [DEBUG] Using proactor: IocpProactor
2024-01-23 18:10:32,840 [INFO] logging in using static token
2024-01-23 18:10:33,891 [INFO] Shard ID 0 has connected to Gateway (Session ID: cad2bb61bb343c1437a5463f1604c5ed).
2024-01-23 18:10:35,922 [INFO] -------------
2024-01-23 18:10:35,922 [INFO] |Fantasy Bot|
2024-01-23 18:10:35,922 [INFO] -------------
2024-01-23 18:10:43,092 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002D37E99C170>
2024-01-23 18:10:57,285 [DEBUG] Using proactor: IocpProactor
2024-01-23 18:10:57,286 [INFO] logging in using static token
2024-01-23 18:10:58,396 [INFO] Shard ID 0 has connected to Gateway (Session ID: 190a20f9c2f861148a503e743000050d).
2024-01-23 18:11:00,445 [INFO] -------------
2024-01-23 18:11:00,445 [INFO] |Fantasy Bot|
2024-01-23 18:11:00,445 [INFO] -------------
2024-01-23 18:11:06,616 [INFO] Message from axon319: +myscore
2024-01-23 18:11:06,619 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 104, in on_message
    query = cursor.execute(f"""
            ^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such function: ROWNUMBER
2024-01-23 18:11:39,724 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001E7D23D4170>
2024-01-23 18:11:52,276 [DEBUG] Using proactor: IocpProactor
2024-01-23 18:11:52,279 [INFO] logging in using static token
2024-01-23 18:11:53,347 [INFO] Shard ID 0 has connected to Gateway (Session ID: f058afd2981d834334569d7efc33ce8a).
2024-01-23 18:11:55,377 [INFO] -------------
2024-01-23 18:11:55,377 [INFO] |Fantasy Bot|
2024-01-23 18:11:55,377 [INFO] -------------
2024-01-23 18:12:19,169 [INFO] Message from axon319: +myscore
2024-01-23 18:12:19,170 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 104, in on_message
    query = cursor.execute(f"""
            ^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such function: ROWNUMBER
2024-01-23 18:12:49,413 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B74423B290>
2024-01-23 18:12:52,771 [DEBUG] Using proactor: IocpProactor
2024-01-23 18:12:52,773 [INFO] logging in using static token
2024-01-23 18:12:53,799 [INFO] Shard ID 0 has connected to Gateway (Session ID: 636cac33e48409fb9bd388c94534512d).
2024-01-23 18:12:55,826 [INFO] -------------
2024-01-23 18:12:55,826 [INFO] |Fantasy Bot|
2024-01-23 18:12:55,826 [INFO] -------------
2024-01-23 18:13:12,170 [INFO] Message from axon319: +myscore
2024-01-23 18:13:12,171 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 104, in on_message
    query = cursor.execute(f"""
            ^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such function: ROWNUMBER
2024-01-23 18:13:30,370 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001EF00CD23F0>
2024-01-23 18:13:33,719 [DEBUG] Using proactor: IocpProactor
2024-01-23 18:13:33,720 [INFO] logging in using static token
2024-01-23 18:13:35,076 [INFO] Shard ID 0 has connected to Gateway (Session ID: bfe87339db310a1e2b88d26bb3c51db3).
2024-01-23 18:13:37,119 [INFO] -------------
2024-01-23 18:13:37,119 [INFO] |Fantasy Bot|
2024-01-23 18:13:37,119 [INFO] -------------
2024-01-23 18:13:56,954 [INFO] Message from axon319: +myscore
2024-01-23 18:15:05,106 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002B7C12CFDD0>
2024-01-23 18:21:22,183 [DEBUG] Using proactor: IocpProactor
2024-01-23 18:21:22,185 [INFO] logging in using static token
2024-01-23 18:21:23,259 [INFO] Shard ID 0 has connected to Gateway (Session ID: 5c34f9bd4e87a1176584a38867c253e2).
2024-01-23 18:21:25,179 [INFO] Message from axon319: +myscore
2024-01-23 18:21:25,285 [INFO] -------------
2024-01-23 18:21:25,285 [INFO] |Fantasy Bot|
2024-01-23 18:21:25,285 [INFO] -------------
2024-01-23 18:21:47,084 [INFO] Message from axon319: +myscore
2024-01-23 18:35:08,609 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001DC8121C080>
2024-01-23 18:37:32,452 [DEBUG] Using proactor: IocpProactor
2024-01-23 18:37:32,454 [INFO] logging in using static token
2024-01-23 18:37:33,759 [INFO] Shard ID 0 has connected to Gateway (Session ID: 9192de7854d6eee1c73c7f80a252fc8e).
2024-01-23 18:37:35,775 [INFO] -------------
2024-01-23 18:37:35,775 [INFO] |Fantasy Bot|
2024-01-23 18:37:35,775 [INFO] -------------
2024-01-23 18:37:37,291 [INFO] Message from axon319: +myscore
2024-01-23 18:38:02,223 [INFO] Message from axon319: +myscore
2024-01-23 18:38:10,512 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000017D7ECC73E0>
2024-01-23 18:38:51,850 [DEBUG] Using proactor: IocpProactor
2024-01-23 18:38:51,851 [INFO] logging in using static token
2024-01-23 18:38:53,122 [INFO] Shard ID 0 has connected to Gateway (Session ID: c3a0b9ec2ae92c6f30ba3d39164022b1).
2024-01-23 18:38:55,150 [INFO] -------------
2024-01-23 18:38:55,150 [INFO] |Fantasy Bot|
2024-01-23 18:38:55,150 [INFO] -------------
2024-01-23 18:38:57,354 [INFO] Message from axon319: +myscore
2024-01-23 18:39:38,020 [INFO] Message from axon319: +myscore
2024-01-23 18:42:09,927 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024CA5582BA0>
2024-01-23 19:02:34,980 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:02:34,981 [INFO] logging in using static token
2024-01-23 19:02:36,066 [INFO] Shard ID 0 has connected to Gateway (Session ID: ea4faf8ddd87ac1149b26d13c5761bcd).
2024-01-23 19:02:38,114 [INFO] -------------
2024-01-23 19:02:38,114 [INFO] |Fantasy Bot|
2024-01-23 19:02:38,114 [INFO] -------------
2024-01-23 19:02:39,774 [INFO] Message from axon319: +standings
2024-01-23 19:02:39,775 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 190, in on_message
    closedCheck = cursor.execute(f"""SELECT in_closed FROM managers WHERE discord_user_id = {userID}""")
                                                                                             ^^^^^^
UnboundLocalError: cannot access local variable 'userID' where it is not associated with a value
2024-01-23 19:03:05,787 [INFO] Message from axon319: +standings open
2024-01-23 19:03:18,597 [INFO] Message from axon319: +standings close
2024-01-23 19:03:18,597 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 190, in on_message
    userID = message.author.id
                               
UnboundLocalError: cannot access local variable 'userID' where it is not associated with a value
2024-01-23 19:03:26,627 [INFO] Message from axon319: +standings closed
2024-01-23 19:03:31,523 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000276F355A090>
2024-01-23 19:04:22,958 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:04:22,960 [INFO] logging in using static token
2024-01-23 19:04:24,154 [INFO] Shard ID 0 has connected to Gateway (Session ID: 4c743a6f47713bdeab2a9b58bf4817b1).
2024-01-23 19:04:26,209 [INFO] -------------
2024-01-23 19:04:26,209 [INFO] |Fantasy Bot|
2024-01-23 19:04:26,209 [INFO] -------------
2024-01-23 19:04:31,649 [INFO] Message from axon319: +standings
2024-01-23 19:04:50,178 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024CEAA33320>
2024-01-23 19:20:37,833 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:20:37,834 [INFO] logging in using static token
2024-01-23 19:20:39,021 [INFO] Shard ID 0 has connected to Gateway (Session ID: eabade4f9d9f5d01c19fc24d5ea529fb).
2024-01-23 19:20:41,046 [INFO] -------------
2024-01-23 19:20:41,046 [INFO] |Fantasy Bot|
2024-01-23 19:20:41,046 [INFO] -------------
2024-01-23 19:20:47,863 [INFO] Message from axon319: +find Beaulo
2024-01-23 19:20:47,864 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 210, in on_message
    query = cursor.execute(f"""WITH PlayerRanking AS (
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: pr.eliminated
2024-01-23 19:21:00,065 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020880763800>
2024-01-23 19:21:06,669 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:21:06,670 [INFO] logging in using static token
2024-01-23 19:21:07,662 [INFO] Shard ID 0 has connected to Gateway (Session ID: 04a9046ac99c56f17e0943d36d4365cc).
2024-01-23 19:21:09,697 [INFO] -------------
2024-01-23 19:21:09,697 [INFO] |Fantasy Bot|
2024-01-23 19:21:09,697 [INFO] -------------
2024-01-23 19:21:13,119 [INFO] Message from axon319: +find Beaulo
2024-01-23 19:22:46,625 [INFO] Message from axon319: +find darkzero
2024-01-23 19:24:40,624 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000223171ADF10>
2024-01-23 19:24:43,490 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:24:43,491 [INFO] logging in using static token
2024-01-23 19:24:44,650 [INFO] Shard ID 0 has connected to Gateway (Session ID: 32a4b02e1406683680b0a03fe9adbd97).
2024-01-23 19:24:46,668 [INFO] -------------
2024-01-23 19:24:46,668 [INFO] |Fantasy Bot|
2024-01-23 19:24:46,668 [INFO] -------------
2024-01-23 19:24:49,171 [INFO] Message from axon319: +find Beaulo
2024-01-23 19:24:55,089 [INFO] Message from axon319: +find darkzero
2024-01-23 19:25:43,334 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000023F4A013320>
2024-01-23 19:26:15,265 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:26:15,266 [INFO] logging in using static token
2024-01-23 19:26:16,299 [INFO] Shard ID 0 has connected to Gateway (Session ID: fd900b7eeab44b487cd172656b8ad4c8).
2024-01-23 19:26:18,326 [INFO] -------------
2024-01-23 19:26:18,326 [INFO] |Fantasy Bot|
2024-01-23 19:26:18,326 [INFO] -------------
2024-01-23 19:26:21,247 [INFO] Message from axon319: +find darkzero
2024-01-23 19:34:29,183 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001AF39A4B770>
2024-01-23 19:34:36,665 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:34:36,666 [INFO] logging in using static token
2024-01-23 19:34:37,752 [INFO] Shard ID 0 has connected to Gateway (Session ID: 099feeaa19f48eb972a68374afc5934b).
2024-01-23 19:34:39,786 [INFO] -------------
2024-01-23 19:34:39,786 [INFO] |Fantasy Bot|
2024-01-23 19:34:39,786 [INFO] -------------
2024-01-23 19:34:46,256 [INFO] Message from axon319: +find darkzero
2024-01-23 19:34:46,258 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 213, in on_message
    query = cursor.execute(
            ^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: pr.max_daily_score
2024-01-23 19:34:59,090 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000027F7BA1CF80>
2024-01-23 19:35:01,763 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:35:01,764 [INFO] logging in using static token
2024-01-23 19:35:02,901 [INFO] Shard ID 0 has connected to Gateway (Session ID: 3241343810b3accf56a74e899ccf5de0).
2024-01-23 19:35:04,936 [INFO] -------------
2024-01-23 19:35:04,936 [INFO] |Fantasy Bot|
2024-01-23 19:35:04,936 [INFO] -------------
2024-01-23 19:35:05,195 [INFO] Message from axon319: +find darkzero
2024-01-23 19:35:38,345 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000206A95286E0>
2024-01-23 19:35:41,310 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:35:41,311 [INFO] logging in using static token
2024-01-23 19:35:42,528 [INFO] Shard ID 0 has connected to Gateway (Session ID: 48a08f1da54eb3094c7ad4211995beed).
2024-01-23 19:35:44,557 [INFO] -------------
2024-01-23 19:35:44,557 [INFO] |Fantasy Bot|
2024-01-23 19:35:44,558 [INFO] -------------
2024-01-23 19:35:45,171 [INFO] Message from axon319: +find darkzero
2024-01-23 19:36:18,932 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000015301562BA0>
2024-01-23 19:37:48,753 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:37:48,754 [INFO] logging in using static token
2024-01-23 19:37:49,806 [INFO] Shard ID 0 has connected to Gateway (Session ID: df9295c5c819e52d6576d4481c9ea69c).
2024-01-23 19:37:51,848 [INFO] -------------
2024-01-23 19:37:51,848 [INFO] |Fantasy Bot|
2024-01-23 19:37:51,848 [INFO] -------------
2024-01-23 19:38:01,503 [INFO] Message from axon319: +find darkzero
2024-01-23 19:38:01,504 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 212, in on_message
    query = cursor.execute(
            ^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "GROUP": syntax error
2024-01-23 19:39:01,118 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001CCFF045220>
2024-01-23 19:39:04,438 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:39:04,439 [INFO] logging in using static token
2024-01-23 19:39:05,492 [INFO] Shard ID 0 has connected to Gateway (Session ID: fae666c64e7d6078ab1d5a62e0e3d479).
2024-01-23 19:39:07,519 [INFO] -------------
2024-01-23 19:39:07,519 [INFO] |Fantasy Bot|
2024-01-23 19:39:07,519 [INFO] -------------
2024-01-23 19:39:15,661 [INFO] Message from axon319: +find darkzero
2024-01-23 19:39:15,662 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 233, in on_message
    (LOWER(subquery.player_name) LIKE LOWER('%{message.content[6:]}%') OR subquery.player_id = '{player_id}')
                                                                                                 ^^^^^^^^^
UnboundLocalError: cannot access local variable 'player_id' where it is not associated with a value
2024-01-23 19:39:36,472 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001384B1DAB70>
2024-01-23 19:39:45,047 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:39:45,049 [INFO] logging in using static token
2024-01-23 19:39:46,096 [INFO] Shard ID 0 has connected to Gateway (Session ID: e02093f22c8e30e04aeb14c01c1b3747).
2024-01-23 19:39:48,126 [INFO] -------------
2024-01-23 19:39:48,126 [INFO] |Fantasy Bot|
2024-01-23 19:39:48,126 [INFO] -------------
2024-01-23 19:39:49,441 [INFO] Message from axon319: +find darkzero
2024-01-23 19:41:58,616 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021C2B46EFF0>
2024-01-23 19:42:01,443 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:42:01,444 [INFO] logging in using static token
2024-01-23 19:42:02,428 [INFO] Shard ID 0 has connected to Gateway (Session ID: 60c5f949c34d65f8defe5f26eaf5c54b).
2024-01-23 19:42:12,569 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:42:12,571 [INFO] logging in using static token
2024-01-23 19:42:13,568 [INFO] Shard ID 0 has connected to Gateway (Session ID: c54171c99016e990d543f8535bfefa27).
2024-01-23 19:42:15,599 [INFO] -------------
2024-01-23 19:42:15,599 [INFO] |Fantasy Bot|
2024-01-23 19:42:15,599 [INFO] -------------
2024-01-23 19:42:17,729 [INFO] Message from axon319: +find darkzero
2024-01-23 19:42:17,730 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 212, in on_message
    query = cursor.execute(
            ^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: subquery.player_name
2024-01-23 19:42:41,661 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001AB758BE060>
2024-01-23 19:42:44,509 [DEBUG] Using proactor: IocpProactor
2024-01-23 19:42:44,510 [INFO] logging in using static token
2024-01-23 19:42:45,474 [INFO] Shard ID 0 has connected to Gateway (Session ID: 0b85ed936c07137e65e8996010a34a72).
2024-01-23 19:42:47,511 [INFO] -------------
2024-01-23 19:42:47,511 [INFO] |Fantasy Bot|
2024-01-23 19:42:47,511 [INFO] -------------
2024-01-23 19:42:53,640 [INFO] Message from axon319: +find darkzero
2024-01-23 19:42:57,679 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000296FFAA94C0>
2024-01-23 20:01:46,891 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:01:46,892 [INFO] logging in using static token
2024-01-23 20:01:47,923 [INFO] Shard ID 0 has connected to Gateway (Session ID: de36a3e8b623119b30235648097f7880).
2024-01-23 20:01:49,952 [INFO] -------------
2024-01-23 20:01:49,952 [INFO] |Fantasy Bot|
2024-01-23 20:01:49,952 [INFO] -------------
2024-01-23 20:01:50,116 [INFO] Message from axon319: +find darkzero
2024-01-23 20:01:50,117 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 210, in on_message
    player_data = cursor.execute(f"""SELECT player_idFROM players WHERE
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: player_idFROM
2024-01-23 20:01:56,190 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002094DD7EBD0>
2024-01-23 20:01:59,183 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:01:59,185 [INFO] logging in using static token
2024-01-23 20:02:00,379 [INFO] Shard ID 0 has connected to Gateway (Session ID: 2fe95c004a1310020f68ceeeea23b3d7).
2024-01-23 20:02:02,428 [INFO] -------------
2024-01-23 20:02:02,428 [INFO] |Fantasy Bot|
2024-01-23 20:02:02,428 [INFO] -------------
2024-01-23 20:02:04,238 [INFO] Message from axon319: +find darkzero
2024-01-23 20:02:45,329 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001844BA6C830>
2024-01-23 20:02:48,320 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:02:48,321 [INFO] logging in using static token
2024-01-23 20:02:49,316 [INFO] Shard ID 0 has connected to Gateway (Session ID: 28e0b38702912b69e9877d84420de259).
2024-01-23 20:02:51,353 [INFO] -------------
2024-01-23 20:02:51,353 [INFO] |Fantasy Bot|
2024-01-23 20:02:51,353 [INFO] -------------
2024-01-23 20:02:52,691 [INFO] Message from axon319: +find darkzero
2024-01-23 20:03:39,769 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001A49A3B83B0>
2024-01-23 20:03:44,822 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:03:44,823 [INFO] logging in using static token
2024-01-23 20:03:45,885 [INFO] Shard ID 0 has connected to Gateway (Session ID: f3f450dd4aa728ae383dd17dac86cd52).
2024-01-23 20:03:47,929 [INFO] -------------
2024-01-23 20:03:47,930 [INFO] |Fantasy Bot|
2024-01-23 20:03:47,930 [INFO] -------------
2024-01-23 20:03:58,375 [INFO] Message from axon319: +find Darkzero
2024-01-23 20:03:58,376 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 216, in on_message
    query = cursor.execute(
            ^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: 131, 132, 133, 134, 135
2024-01-23 20:04:48,754 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001C0F1DD2AE0>
2024-01-23 20:04:51,715 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:04:51,716 [INFO] logging in using static token
2024-01-23 20:04:52,832 [INFO] Shard ID 0 has connected to Gateway (Session ID: edc423623d0c3941b5b9dfdafa8cf2af).
2024-01-23 20:04:54,858 [INFO] -------------
2024-01-23 20:04:54,858 [INFO] |Fantasy Bot|
2024-01-23 20:04:54,858 [INFO] -------------
2024-01-23 20:04:57,831 [INFO] Message from axon319: +find Darkzero
2024-01-23 20:04:57,833 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 216, in on_message
    query = cursor.execute(
            ^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: 131, 132, 133, 134, 135
2024-01-23 20:05:28,415 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002A07EC3EFF0>
2024-01-23 20:05:31,303 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:05:31,304 [INFO] logging in using static token
2024-01-23 20:05:32,444 [INFO] Shard ID 0 has connected to Gateway (Session ID: 23c5dcfea921f1a0b19edc3c1505c0b0).
2024-01-23 20:05:34,463 [INFO] -------------
2024-01-23 20:05:34,463 [INFO] |Fantasy Bot|
2024-01-23 20:05:34,463 [INFO] -------------
2024-01-23 20:05:36,437 [INFO] Message from axon319: +find Darkzero
2024-01-23 20:05:36,441 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 236, in on_message
    query = cursor.execute(queryTest)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: 131, 132, 133, 134, 135
2024-01-23 20:06:33,592 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000204C1959EB0>
2024-01-23 20:06:36,545 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:06:36,546 [INFO] logging in using static token
2024-01-23 20:06:37,624 [INFO] Shard ID 0 has connected to Gateway (Session ID: 8f5b37262e89cd86fb5a150f5bb8ac8e).
2024-01-23 20:06:39,646 [INFO] -------------
2024-01-23 20:06:39,646 [INFO] |Fantasy Bot|
2024-01-23 20:06:39,646 [INFO] -------------
2024-01-23 20:06:45,674 [INFO] Message from axon319: +find Darkzero
2024-01-23 20:06:45,678 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 236, in on_message
    query = cursor.execute(queryTest)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: near "<": syntax error
2024-01-23 20:07:13,559 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024ED1AA3770>
2024-01-23 20:07:16,293 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:07:16,294 [INFO] logging in using static token
2024-01-23 20:07:17,266 [INFO] Shard ID 0 has connected to Gateway (Session ID: d76ff4414c43a8fc092ed2f2c976c07f).
2024-01-23 20:07:19,310 [INFO] -------------
2024-01-23 20:07:19,310 [INFO] |Fantasy Bot|
2024-01-23 20:07:19,310 [INFO] -------------
2024-01-23 20:07:19,631 [INFO] Message from axon319: +find Darkzero
2024-01-23 20:07:25,842 [INFO] Message from axon319: +find W7m
2024-01-23 20:07:42,204 [INFO] Message from axon319: +find beaulo
2024-01-23 20:08:29,123 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002863E6A66F0>
2024-01-23 20:08:44,631 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:08:44,632 [INFO] logging in using static token
2024-01-23 20:08:45,744 [INFO] Shard ID 0 has connected to Gateway (Session ID: 0bc44ab87417fd6b19c057979456e42d).
2024-01-23 20:08:47,817 [INFO] -------------
2024-01-23 20:08:47,817 [INFO] |Fantasy Bot|
2024-01-23 20:08:47,817 [INFO] -------------
2024-01-23 20:08:48,727 [INFO] Message from axon319: +find beaulo
2024-01-23 20:08:48,730 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 239, in on_message
    df = df[['Rank', 'ID' 'Name', 'Team', 'Total Score']]
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\frame.py", line 4096, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\indexes\base.py", line 6199, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\indexes\base.py", line 6251, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['IDName'] not in index"
2024-01-23 20:08:55,334 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002ABA6C694C0>
2024-01-23 20:08:58,235 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:08:58,236 [INFO] logging in using static token
2024-01-23 20:08:59,393 [INFO] Shard ID 0 has connected to Gateway (Session ID: 0352d8916b0643f0a080faba55889733).
2024-01-23 20:09:01,485 [INFO] -------------
2024-01-23 20:09:01,485 [INFO] |Fantasy Bot|
2024-01-23 20:09:01,485 [INFO] -------------
2024-01-23 20:09:03,162 [INFO] Message from axon319: +find beaulo
2024-01-23 20:09:09,432 [INFO] Message from axon319: +find Bleed
2024-01-23 20:09:41,498 [INFO] Message from axon319: +find Reeps
2024-01-23 20:09:45,264 [INFO] Message from axon319: +find Bleed
2024-01-23 20:09:48,588 [INFO] Message from axon319: +standings
2024-01-23 20:09:54,838 [INFO] Message from axon319: +standings closed
2024-01-23 20:09:59,934 [INFO] Message from axon319: +standings open
2024-01-23 20:10:15,612 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001CEFFE1B770>
2024-01-23 20:10:22,940 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:10:22,941 [INFO] logging in using static token
2024-01-23 20:10:24,072 [INFO] Shard ID 0 has connected to Gateway (Session ID: c8eabfde131ebb974918f5caadce6ae8).
2024-01-23 20:10:26,098 [INFO] -------------
2024-01-23 20:10:26,098 [INFO] |Fantasy Bot|
2024-01-23 20:10:26,098 [INFO] -------------
2024-01-23 20:10:30,800 [INFO] Message from axon319: +myscore
2024-01-23 20:10:43,891 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002304DF74D70>
2024-01-23 20:16:19,963 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:16:19,964 [INFO] logging in using static token
2024-01-23 20:16:21,055 [INFO] Shard ID 0 has connected to Gateway (Session ID: b02961515e2338d8d0a943070ab292e5).
2024-01-23 20:16:23,161 [INFO] -------------
2024-01-23 20:16:23,161 [INFO] |Fantasy Bot|
2024-01-23 20:16:23,161 [INFO] -------------
2024-01-23 20:16:40,940 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001A918DD39B0>
2024-01-23 20:16:43,647 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:16:43,648 [INFO] logging in using static token
2024-01-23 20:16:44,992 [INFO] Shard ID 0 has connected to Gateway (Session ID: 73b67d5cf93e79d62280c36946eb866c).
2024-01-23 20:16:47,014 [INFO] -------------
2024-01-23 20:16:47,014 [INFO] |Fantasy Bot|
2024-01-23 20:16:47,014 [INFO] -------------
2024-01-23 20:16:47,793 [INFO] Message from axon319: +market
2024-01-23 20:16:51,988 [INFO] Message from axon319: +market close
2024-01-23 20:17:12,345 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F1E3EC94C0>
2024-01-23 20:17:15,231 [DEBUG] Using proactor: IocpProactor
2024-01-23 20:17:15,233 [INFO] logging in using static token
2024-01-23 20:17:16,276 [INFO] Shard ID 0 has connected to Gateway (Session ID: 111536838813b69d54e3ce174c364cf5).
2024-01-23 20:17:18,305 [INFO] -------------
2024-01-23 20:17:18,305 [INFO] |Fantasy Bot|
2024-01-23 20:17:18,305 [INFO] -------------
2024-01-23 20:17:22,533 [INFO] Message from axon319: +market open
2024-01-23 20:17:26,547 [INFO] Message from axon319: +market close
2024-01-23 20:18:03,601 [INFO] Message from axon319: +market open
2024-01-23 20:18:40,222 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000014B278D3F50>
2024-01-24 17:02:14,117 [DEBUG] Using proactor: IocpProactor
2024-01-24 17:02:14,120 [INFO] logging in using static token
2024-01-24 17:02:15,327 [INFO] Shard ID 0 has connected to Gateway (Session ID: b32ccee145b600779221cf600d71fc5d).
2024-01-24 17:02:17,399 [INFO] -------------
2024-01-24 17:02:17,399 [INFO] |Fantasy Bot|
2024-01-24 17:02:17,399 [INFO] -------------
2024-01-24 18:56:16,116 [INFO] Shard ID 0 has successfully RESUMED session b32ccee145b600779221cf600d71fc5d.
2024-01-24 19:59:05,574 [INFO] Shard ID 0 has successfully RESUMED session b32ccee145b600779221cf600d71fc5d.
2024-01-24 22:55:12,886 [INFO] Shard ID 0 has successfully RESUMED session b32ccee145b600779221cf600d71fc5d.
2024-01-25 22:33:36,571 [DEBUG] Using proactor: IocpProactor
2024-01-25 22:33:36,573 [INFO] logging in using static token
2024-01-25 22:33:37,863 [INFO] Shard ID 0 has connected to Gateway (Session ID: 0e4c75c41617ddab7a18a5fc53285477).
2024-01-25 22:33:39,940 [INFO] -------------
2024-01-25 22:33:39,940 [INFO] |Fantasy Bot|
2024-01-25 22:33:39,940 [INFO] -------------
2024-01-25 22:34:13,404 [INFO] Message from axon319: +signup
2024-01-25 22:34:13,405 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 403, in on_message
    if closedCheck[0] == True:
       ~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-25 22:34:42,626 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000027A1C22B200>
2024-01-25 22:34:45,486 [DEBUG] Using proactor: IocpProactor
2024-01-25 22:34:45,487 [INFO] logging in using static token
2024-01-25 22:34:46,759 [INFO] Shard ID 0 has connected to Gateway (Session ID: ffeef477ea7ced5c07eb22bb7749359e).
2024-01-25 22:34:48,835 [INFO] -------------
2024-01-25 22:34:48,835 [INFO] |Fantasy Bot|
2024-01-25 22:34:48,836 [INFO] -------------
2024-01-25 22:34:49,142 [INFO] Message from axon319: +signup
2024-01-25 22:34:49,144 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 403, in on_message
    if closedCheck is not None or closedCheck[0] == True:
                                  ~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-25 22:35:09,084 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000016D6B93B800>
2024-01-25 22:35:12,234 [DEBUG] Using proactor: IocpProactor
2024-01-25 22:35:12,235 [INFO] logging in using static token
2024-01-25 22:35:13,664 [INFO] Shard ID 0 has connected to Gateway (Session ID: 7916561600010a70fa572a5054a88d1f).
2024-01-25 22:35:15,738 [INFO] -------------
2024-01-25 22:35:15,738 [INFO] |Fantasy Bot|
2024-01-25 22:35:15,738 [INFO] -------------
2024-01-25 22:35:19,798 [INFO] Message from axon319: +signup
2024-01-25 22:38:06,158 [INFO] Message from axon319: +market
2024-01-25 22:39:40,954 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000013281514170>
2024-01-25 22:39:54,311 [DEBUG] Using proactor: IocpProactor
2024-01-25 22:39:54,312 [INFO] logging in using static token
2024-01-25 22:39:55,521 [INFO] Shard ID 0 has connected to Gateway (Session ID: 12cf949586bf91e21002f58fc2b5f9cc).
2024-01-25 22:39:57,589 [INFO] -------------
2024-01-25 22:39:57,589 [INFO] |Fantasy Bot|
2024-01-25 22:39:57,589 [INFO] -------------
2024-01-25 22:40:05,127 [INFO] Message from axon319: +pick Reeps
2024-01-25 22:40:05,128 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 445, in on_message
    query2 = cursor.execute(f"""
             ^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: og.discord_user_id
2024-01-25 22:40:36,302 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D8CE31C050>
2024-01-25 22:40:39,885 [DEBUG] Using proactor: IocpProactor
2024-01-25 22:40:39,886 [INFO] logging in using static token
2024-01-25 22:40:41,167 [INFO] Shard ID 0 has connected to Gateway (Session ID: df289095178cbe944b57203c91022ddc).
2024-01-25 22:40:43,242 [INFO] -------------
2024-01-25 22:40:43,242 [INFO] |Fantasy Bot|
2024-01-25 22:40:43,242 [INFO] -------------
2024-01-25 22:40:46,125 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000217A63EC080>
2024-01-25 22:41:04,461 [DEBUG] Using proactor: IocpProactor
2024-01-25 22:41:04,462 [INFO] logging in using static token
2024-01-25 22:41:05,826 [INFO] Shard ID 0 has connected to Gateway (Session ID: de14cdecc947c69012ecf9886f1f2a57).
2024-01-25 22:41:07,871 [INFO] -------------
2024-01-25 22:41:07,871 [INFO] |Fantasy Bot|
2024-01-25 22:41:07,871 [INFO] -------------
2024-01-25 22:41:15,035 [INFO] Message from axon319: +pick Reeps
2024-01-25 22:41:19,085 [INFO] Message from axon319: +pick Nath
2024-01-25 22:41:23,389 [INFO] Message from axon319: +pick Beaulo
2024-01-25 22:41:27,046 [INFO] Message from axon319: +pick Kheyze
2024-01-25 22:41:34,667 [INFO] Message from axon319: +pick Herdz
2024-01-25 22:41:53,587 [INFO] Message from axon319: +myteam
2024-01-25 22:42:08,385 [INFO] Message from axon319: +pick Pyon
2024-01-25 22:42:11,339 [INFO] Message from axon319: +myteam
2024-01-25 22:43:39,641 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002056201E4B0>
2024-01-25 22:43:54,467 [DEBUG] Using proactor: IocpProactor
2024-01-25 22:43:54,468 [INFO] logging in using static token
2024-01-25 22:43:55,795 [INFO] Shard ID 0 has connected to Gateway (Session ID: 35c6677d1eae66fa6e6ee229a2d69f76).
2024-01-25 22:43:57,857 [INFO] -------------
2024-01-25 22:43:57,857 [INFO] |Fantasy Bot|
2024-01-25 22:43:57,857 [INFO] -------------
2024-01-25 22:45:13,710 [INFO] Message from luffy319: +signup
2024-01-25 22:45:29,061 [INFO] Message from luffy319: +pick Terdsta
2024-01-25 22:46:17,131 [INFO] Message from luffy319: +pick RIN
2024-01-25 22:47:08,045 [INFO] Message from luffy319: +pick KDS
2024-01-25 22:47:20,281 [INFO] Message from luffy319: +pick Geo
2024-01-25 22:47:26,016 [INFO] Message from luffy319: +myteam
2024-01-25 22:47:44,019 [INFO] Message from luffy319: +pick cameraman
2024-01-25 22:47:47,968 [INFO] Message from luffy319: +myteam
2024-01-25 23:02:26,333 [INFO] Message from luffy319: +myteam
2024-01-25 23:02:34,477 [INFO] Message from axon319: +myteam
2024-01-25 23:02:58,400 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 646, in on_message
    cursor.execute(f"""UPDATE players SET eliminated = TRUE, updated_at = NOW() WHERE team_name = '{teamName}'""")
sqlite3.OperationalError: no such function: NOW
2024-01-25 23:03:57,718 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000112CA6DBF80>
2024-01-25 23:04:05,969 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:04:05,970 [INFO] logging in using static token
2024-01-25 23:04:07,295 [INFO] Shard ID 0 has connected to Gateway (Session ID: 40753f3c5e4b6abf7dde6570054f04ab).
2024-01-25 23:04:09,364 [INFO] -------------
2024-01-25 23:04:09,364 [INFO] |Fantasy Bot|
2024-01-25 23:04:09,365 [INFO] -------------
2024-01-25 23:04:15,282 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 646, in on_message
    cursor.execute(f"""UPDATE players SET eliminated = TRUE, updated_at = NOW() WHERE team_name = '{teamName}'""")
sqlite3.OperationalError: no such function: NOW
2024-01-25 23:04:21,870 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000013F4B50AAE0>
2024-01-25 23:04:24,579 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:04:24,580 [INFO] logging in using static token
2024-01-25 23:04:25,770 [INFO] Shard ID 0 has connected to Gateway (Session ID: 21c0ae6b6201f2b44fcb108c0a05e83b).
2024-01-25 23:04:27,855 [INFO] -------------
2024-01-25 23:04:27,855 [INFO] |Fantasy Bot|
2024-01-25 23:04:27,855 [INFO] -------------
2024-01-25 23:04:47,836 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 646, in on_message
    cursor.execute(f"""UPDATE players SET eliminated = TRUE, updated_at = datetime('now') WHERE team_name = '{teamName}'""")
sqlite3.OperationalError: database is locked
2024-01-25 23:04:57,731 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 646, in on_message
    cursor.execute(f"""UPDATE players SET eliminated = TRUE, updated_at = datetime('now') WHERE team_name = '{teamName}'""")
sqlite3.OperationalError: database is locked
2024-01-25 23:05:11,449 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B6229DBE30>
2024-01-25 23:05:14,541 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:05:14,542 [INFO] logging in using static token
2024-01-25 23:05:15,749 [INFO] Shard ID 0 has connected to Gateway (Session ID: 9ca253c311abe4da45ad23564f4f83bc).
2024-01-25 23:05:17,794 [INFO] -------------
2024-01-25 23:05:17,794 [INFO] |Fantasy Bot|
2024-01-25 23:05:17,794 [INFO] -------------
2024-01-25 23:06:12,864 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002A4C3AA2A50>
2024-01-25 23:06:15,919 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:06:15,920 [INFO] logging in using static token
2024-01-25 23:06:17,009 [INFO] Shard ID 0 has connected to Gateway (Session ID: 3313aab5307f84eca7d8e06346697002).
2024-01-25 23:06:19,038 [INFO] -------------
2024-01-25 23:06:19,038 [INFO] |Fantasy Bot|
2024-01-25 23:06:19,038 [INFO] -------------
2024-01-25 23:07:09,772 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020760E7EBD0>
2024-01-25 23:07:47,965 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:07:47,966 [INFO] logging in using static token
2024-01-25 23:07:49,284 [INFO] Shard ID 0 has connected to Gateway (Session ID: 07b4e694342278f02b070b1e50bd0a54).
2024-01-25 23:07:51,360 [INFO] -------------
2024-01-25 23:07:51,360 [INFO] |Fantasy Bot|
2024-01-25 23:07:51,361 [INFO] -------------
2024-01-25 23:08:17,171 [INFO] Message from axon319: +myteam
2024-01-25 23:08:31,316 [INFO] Message from luffy319: +request Rin Reeps
2024-01-25 23:08:36,856 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 382, in on_message
    cursor.execute(f"""INSERT INTO trades (requester_id, requester_player_id, requestee_player_id, is_accepted, is_open) VALUES
sqlite3.OperationalError: database is locked
2024-01-25 23:09:12,314 [INFO] Message from luffy319: +request Rin Reeps
2024-01-25 23:09:17,867 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 382, in on_message
    cursor.execute(f"""INSERT INTO trades (requester_id, requester_player_id, requestee_player_id, is_accepted, is_open) VALUES
sqlite3.OperationalError: database is locked
2024-01-25 23:10:08,465 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000193F2C71850>
2024-01-25 23:11:57,845 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:11:57,847 [INFO] logging in using static token
2024-01-25 23:12:00,036 [INFO] Shard ID 0 has connected to Gateway (Session ID: 1f01d70bc16e15456c69af5f16336fae).
2024-01-25 23:12:02,097 [INFO] -------------
2024-01-25 23:12:02,097 [INFO] |Fantasy Bot|
2024-01-25 23:12:02,098 [INFO] -------------
2024-01-25 23:12:21,415 [INFO] Message from luffy319: +request Rin Reeps
2024-01-25 23:12:39,288 [INFO] Shard ID 0 has successfully RESUMED session 1f01d70bc16e15456c69af5f16336fae.
2024-01-25 23:12:39,288 [INFO] Message from axon319: +opentrades
2024-01-25 23:14:51,986 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001B4A78265A0>
2024-01-25 23:14:54,986 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:14:54,987 [INFO] logging in using static token
2024-01-25 23:14:56,071 [INFO] Shard ID 0 has connected to Gateway (Session ID: 7f66ae73edb1c3bd1b6dbfe7ff5a2a54).
2024-01-25 23:14:58,096 [INFO] -------------
2024-01-25 23:14:58,096 [INFO] |Fantasy Bot|
2024-01-25 23:14:58,096 [INFO] -------------
2024-01-25 23:15:02,333 [INFO] Message from luffy319: +request Rin Reeps
2024-01-25 23:15:16,725 [INFO] Message from luffy319: +myteam
2024-01-25 23:15:32,992 [INFO] Message from luffy319: +request 200 Canadian
2024-01-25 23:15:57,973 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000014563AE0260>
2024-01-25 23:16:06,249 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:16:06,250 [INFO] logging in using static token
2024-01-25 23:16:07,411 [INFO] Shard ID 0 has connected to Gateway (Session ID: 97cb0e6d5b6631de86e78c2ea1b7e444).
2024-01-25 23:16:09,484 [INFO] -------------
2024-01-25 23:16:09,484 [INFO] |Fantasy Bot|
2024-01-25 23:16:09,484 [INFO] -------------
2024-01-25 23:16:14,472 [INFO] Message from luffy319: +request Rin Canadian
2024-01-25 23:16:23,066 [INFO] Message from luffy319: +request Rin Dmaly
2024-01-25 23:16:36,804 [INFO] Message from luffy319: +request Rin Yass
2024-01-25 23:16:44,046 [INFO] Message from axon319: +opentrades
2024-01-25 23:17:51,702 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F54B6E49E0>
2024-01-25 23:17:58,828 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:17:58,829 [INFO] logging in using static token
2024-01-25 23:18:00,064 [INFO] Shard ID 0 has connected to Gateway (Session ID: e11b049d4cdfff1d427014df91fbb82f).
2024-01-25 23:18:02,090 [INFO] -------------
2024-01-25 23:18:02,090 [INFO] |Fantasy Bot|
2024-01-25 23:18:02,090 [INFO] -------------
2024-01-25 23:18:03,192 [INFO] Message from axon319: +opentrades
2024-01-25 23:18:15,761 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 635, in on_message
    cursor.execute(f"""UPDATE trades SET is_accepted = TRUE, is_open = FALSE, updated_at = datetime('now') WHERE trade_id = {tradeID}""")
sqlite3.OperationalError: no such column: updated_at
2024-01-25 23:18:57,741 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001A8F0A01100>
2024-01-25 23:22:33,167 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:22:33,169 [INFO] logging in using static token
2024-01-25 23:22:34,264 [INFO] Shard ID 0 has connected to Gateway (Session ID: 0e49a29fdd2396c3a68ccc854cc8e276).
2024-01-25 23:22:36,285 [INFO] -------------
2024-01-25 23:22:36,285 [INFO] |Fantasy Bot|
2024-01-25 23:22:36,285 [INFO] -------------
2024-01-25 23:22:42,799 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000292DA971D00>
2024-01-25 23:23:03,516 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:23:03,517 [INFO] logging in using static token
2024-01-25 23:23:04,868 [INFO] Shard ID 0 has connected to Gateway (Session ID: 6f644a8d76092066e251ce995a18c813).
2024-01-25 23:23:06,913 [INFO] -------------
2024-01-25 23:23:06,913 [INFO] |Fantasy Bot|
2024-01-25 23:23:06,913 [INFO] -------------
2024-01-25 23:23:07,545 [INFO] Message from axon319: +opentrades
2024-01-25 23:23:19,776 [INFO] Message from luffy319: +myteam
2024-01-25 23:26:36,182 [INFO] Message from luffy319: +request Terdsta Cyber
2024-01-25 23:26:53,289 [INFO] Message from axon319: +myteam
2024-01-25 23:27:03,554 [INFO] Message from axon319: +request 186 Cyber
2024-01-25 23:27:11,036 [INFO] Message from axon319: +opentrades
2024-01-25 23:27:25,057 [INFO] Message from axon319: +opentrades
2024-01-25 23:28:45,262 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001EB6217F7D0>
2024-01-25 23:28:48,182 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:28:48,183 [INFO] logging in using static token
2024-01-25 23:28:49,180 [INFO] Shard ID 0 has connected to Gateway (Session ID: 81524937a6617d063317d61e2a49b702).
2024-01-25 23:28:51,212 [INFO] -------------
2024-01-25 23:28:51,212 [INFO] |Fantasy Bot|
2024-01-25 23:28:51,212 [INFO] -------------
2024-01-25 23:28:53,692 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 630, in on_message
    manager_id = data[0]
                 ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-25 23:29:02,611 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001C2F2E2E4B0>
2024-01-25 23:29:05,927 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:29:05,928 [INFO] logging in using static token
2024-01-25 23:29:07,092 [INFO] Shard ID 0 has connected to Gateway (Session ID: 78ab659b1093386600ccb9119b33ec8c).
2024-01-25 23:29:09,132 [INFO] -------------
2024-01-25 23:29:09,133 [INFO] |Fantasy Bot|
2024-01-25 23:29:09,133 [INFO] -------------
2024-01-25 23:30:19,275 [INFO] Message from axon319: +myteam
2024-01-25 23:30:34,254 [INFO] Message from axon319: +request Nath Canadian
2024-01-25 23:30:45,427 [INFO] Message from luffy319: +request Geo Canadian
2024-01-25 23:30:51,494 [INFO] Message from axon319: +opentrades
2024-01-25 23:31:04,998 [ERROR] Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Axon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Axon\Desktop\Personal\Projects\Discord Bot\Poll-Bot\FantasyBot\FantasyLeagueBot\fantasyBotBackend.py", line 635, in on_message
    cursor.execute(f"""UPDATE trades SET is_accepted = TRUE, is_open = FALSE, date = datetime('now') WHERE trade_id = {tradeID} or player_id = {requested_player_id}""")
sqlite3.OperationalError: no such column: player_id
2024-01-25 23:31:25,577 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001F3E401C080>
2024-01-25 23:31:28,870 [DEBUG] Using proactor: IocpProactor
2024-01-25 23:31:28,871 [INFO] logging in using static token
2024-01-25 23:31:30,282 [INFO] Shard ID 0 has connected to Gateway (Session ID: a9c3272d0196bb569f66c252a23b48b5).
2024-01-25 23:31:32,040 [INFO] Message from axon319: +opentrades
2024-01-25 23:31:32,337 [INFO] -------------
2024-01-25 23:31:32,337 [INFO] |Fantasy Bot|
2024-01-25 23:31:32,337 [INFO] -------------
2024-01-25 23:31:44,390 [INFO] Message from axon319: +opentrades
2024-01-25 23:31:50,375 [ERROR] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001C77FB831D0>
